.TH "AcceleratorModel::Beamline::TRK< T >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AcceleratorModel::Beamline::TRK< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AcceleratorModel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTRK\fP (T &aT)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBComponentFrame\fP *frame)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T & \fB_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class AcceleratorModel::Beamline::TRK< T >"
Wrapper used by for template<T> void \fBTrack(T&)\fP function\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
