.TH "AcceleratorSupport" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AcceleratorSupport
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPosition\fP (double s, double x, double z)"
.br
.ti -1c
.RI "double \fBGetArcPosition\fP () const"
.br
.ti -1c
.RI "\fBPoint2D\fP \fBGetLocation\fP () const"
.br
.ti -1c
.RI "double \fBDistanceTo\fP (const \fBAcceleratorSupport\fP &aSupport) const"
.br
.ti -1c
.RI "void \fBSetOffset\fP (double x, double y, double z)"
.br
.ti -1c
.RI "void \fBSetOffset\fP (const \fBVector3D\fP &X)"
.br
.ti -1c
.RI "const \fBVector3D\fP & \fBGetOffset\fP () const"
.br
.ti -1c
.RI "const \fBVector3D\fP & \fBIncrementOffset\fP (double dx, double dy, double dz)"
.br
.ti -1c
.RI "const \fBVector3D\fP & \fBIncrementOffset\fP (const \fBVector3D\fP &dX)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSupportStructure\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
