.TH "AMBufferManager< M, B, D >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AMBufferManager< M, B, D >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddBuffer\fP (B *buf)"
.br
.ti -1c
.RI "bool \fBRemoveBuffer\fP (B *buf)"
.br
.ti -1c
.RI "void \fBClearAllBuffers\fP ()"
.br
.ti -1c
.RI "void \fBSendToBuffers\fP (const M &monitor, const D &data)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetDefaultBuffer\fP (B *buf)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
