.TH "ApertureSurvey" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApertureSurvey
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSurveyType\fP { \fBpoints_per_element\fP, \fBdistance\fP, \fBabs_distance\fP }
.RI "Mode for survey\&. Changes how step is interpreted\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBApertureSurvey\fP (\fBAcceleratorModel\fP *model, std::ostream *os, \fBSurveyType\fP mode, double step)"
.br
.ti -1c
.RI "void \fBApertureSurvey\fP (\fBAcceleratorModel\fP *model, string file_name, \fBSurveyType\fP mode, double step)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Survey an accelerator and find the aperture at each step\&.
.PP
At each point the aperture is measured by bisection search, using the PointInside() method of the aperture attached to the element\&. This makes it useful for debugging the whole aperture system\&.
.PP
Output file contains the columns:
.PP
The element's name, type, s_end, length
.PP
Position s
.PP
\fBAperture\fP limit in plus and minus x and y directions ap_px ap_mx ap_py ap_my 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBApertureSurvey::SurveyType\fP"

.PP
Mode for survey\&. Changes how step is interpreted\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIpoints_per_element \fP\fP
Record \fIstep\fP times per element, e\&.g\&. 1: just at start, 2: start and end, 3: start, end and middle\&. 
.TP
\fB\fIdistance \fP\fP
Record every \fIstep\fP distance, within each element\&. Include start and end of each element\&. 
.TP
\fB\fIabs_distance \fP\fP
Record every \fIstep\fP distance, along \fImodel\fP\&. 
.SH "Function Documentation"
.PP 
.SS "void ApertureSurvey::ApertureSurvey (\fBAcceleratorModel\fP * model, std::ostream * os, \fBSurveyType\fP mode, double step)"
Run aperture survey 
.PP
\fBParameters:\fP
.RS 4
\fImodel\fP The accelerator mode 
.br
\fIos\fP Output stream 
.br
\fImode\fP Stepping mode 
.br
\fIstep\fP Definition depends on \fImode\fP 
.RE
.PP

.SS "void ApertureSurvey::ApertureSurvey (\fBAcceleratorModel\fP * model, string file_name, \fBSurveyType\fP mode, double step)"
Run aperture survey 
.PP
\fBParameters:\fP
.RS 4
\fImodel\fP The accelerator mode 
.br
\fIfilename\fP Filename to output to 
.br
\fImode\fP Stepping mode 
.br
\fIstep\fP Definition depends on \fImode\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
