.TH "ApplySimpleDrift" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApplySimpleDrift
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApplySimpleDrift\fP (double len)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBPSvector\fP &x) const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBTPSMoments\fP< 2 > &s) const"
.br
.ti -1c
.RI "void \fBApply\fP (\fBTPSMoments\fP< 3 > &s) const"
.br
.ti -1c
.RI "template<class T > void \fBoperator()\fP (T &s) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions for apply simple drift spaces\&. We provide these functions for effeciency: since drift spaces generally make up half the number of elements in a beamline, we provide special 'tuned' routines for speeding the drifts up\&. Apply a simple drift 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ApplySimpleDrift::ApplySimpleDrift (double len)\fC [inline]\fP, \fC [explicit]\fP"
Apply to single vector 
.SH "Member Function Documentation"
.PP 
.SS "void ApplySimpleDrift::Apply (\fBTPSMoments\fP< 2 > & s) const\fC [inline]\fP"
apply to 4D phase space moments 
.SS "void ApplySimpleDrift::Apply (\fBTPSMoments\fP< 3 > & s) const\fC [inline]\fP"
apply to 6D phase space moments 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
