.TH "ATL2D" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ATL2D
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBATLMode\fP { \fBincrement\fP, \fBabsolute\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBATL2D\fP (double anA, const AcceleratorSupportList &supports, const \fBPoint2D\fP refPoint=\fBPoint2D\fP(0, 0), ifstream *evecTFile=nullptr, ifstream *evalFile=nullptr)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "double \fBDoStep\fP (double dt)"
.br
.ti -1c
.RI "void \fBRecordOffsets\fP (std::ostream &os) const"
.br
.ti -1c
.RI "double \fBGetTime\fP () const"
.br
.ti -1c
.RI "void \fBSetRandomSeed\fP (unsigned int nseed)"
.br
.ti -1c
.RI "unsigned int \fBGetRandomSeed\fP () const"
.br
.ti -1c
.RI "void \fBResetRandomSeed\fP ()"
.br
.ti -1c
.RI "bool \fBSetATLMode\fP (const ATLMode mode)"
.br
.ti -1c
.RI "bool \fBSetVibration\fP (const double vrms)"
.br
.ti -1c
.RI "void \fBRecordEigenSystem\fP (ofstream *evecTFile, ofstream *evalFile)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
