.TH "basic_echo_ostream< T, Tr >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_echo_ostream< T, Tr >
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_ostream< T, Tr >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBecho_streambuf\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_echo_ostream\fP (std::basic_ostream< T, Tr > &first, std::basic_ostream< T, Tr > &second)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
