.TH "basic_echo_ostream< T, Tr >::echo_streambuf" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_echo_ostream< T, Tr >::echo_streambuf
.SH SYNOPSIS
.br
.PP
.PP
Inherits basic_streambuf< T, Tr >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBecho_streambuf\fP (std::basic_ostream< T, Tr > &os1, std::basic_ostream< T, Tr > &os2)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int_type \fBoverflow\fP (int_type c)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
