.TH "BeamData" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BeamData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBok\fP () const"
.br
.ti -1c
.RI "double \fBgamma_x\fP () const"
.br
.ti -1c
.RI "double \fBgamma_y\fP () const"
.br
.ti -1c
.RI "double \fBsigma_x\fP () const"
.br
.ti -1c
.RI "double \fBsigma_y\fP () const"
.br
.ti -1c
.RI "double \fBsigma_xp\fP () const"
.br
.ti -1c
.RI "double \fBsigma_yp\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBbeta_x\fP"
.br
.ti -1c
.RI "double \fBbeta_y\fP"
.br
.ti -1c
.RI "double \fBalpha_x\fP"
.br
.ti -1c
.RI "double \fBalpha_y\fP"
.br
.ti -1c
.RI "double \fBemit_x\fP"
.br
.ti -1c
.RI "double \fBemit_y\fP"
.br
.ti -1c
.RI "double \fBsig_dp\fP"
.br
.ti -1c
.RI "double \fBsig_z\fP"
.br
.ti -1c
.RI "double \fBx0\fP"
.br
.ti -1c
.RI "double \fBxp0\fP"
.br
.ti -1c
.RI "double \fBy0\fP"
.br
.ti -1c
.RI "double \fByp0\fP"
.br
.ti -1c
.RI "double \fBct0\fP"
.br
.ti -1c
.RI "double \fBp0\fP"
.br
.ti -1c
.RI "double \fBc_xy\fP"
.br
.ti -1c
.RI "double \fBc_xyp\fP"
.br
.ti -1c
.RI "double \fBc_xpy\fP"
.br
.ti -1c
.RI "double \fBc_xpyp\fP"
.br
.ti -1c
.RI "double \fBDx\fP"
.br
.ti -1c
.RI "double \fBDxp\fP"
.br
.ti -1c
.RI "double \fBDy\fP"
.br
.ti -1c
.RI "double \fBDyp\fP"
.br
.ti -1c
.RI "double \fBcharge\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
