.TH "BPM" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BPM
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonitor\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBuffer\fP"
.br
.ti -1c
.RI "struct \fBData\fP"
.br
.ti -1c
.RI "class \fBResponse\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBAMBufferManager\fP< \fBBPM\fP, \fBBuffer\fP, \fBData\fP > \fBBufferManager\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBPM\fP (const string &\fBid\fP, double len=0, double mpos=0)"
.br
.ti -1c
.RI "void \fBSetResolution\fP (double xr, double yr)"
.br
.ti -1c
.RI "double \fBSetRes\fP (double r)"
.br
.ti -1c
.RI "void \fBSetScale\fP (double xs, double ys)"
.br
.ti -1c
.RI "\fBResponse\fP * \fBSetResponse\fP (\fBResponse\fP *)"
.br
.ti -1c
.RI "virtual void \fBMakeMeasurement\fP (const \fBBunch\fP &aBunch)"
.br
.ti -1c
.RI "virtual int \fBGetIndex\fP () const"
.br
.ti -1c
.RI "virtual const string & \fBGetType\fP () const"
.br
.ti -1c
.RI "virtual void \fBPrepareTracker\fP (\fBComponentTracker\fP &aTracker)"
.br
.ti -1c
.RI "virtual \fBModelElement\fP * \fBCopy\fP () const"
.br
.ti -1c
.RI "void \fBAddBuffer\fP (\fBBuffer\fP *abuffer)"
.br
.ti -1c
.RI "bool \fBRemoveBuffer\fP (\fBBuffer\fP *aBuffer)"
.br
.ti -1c
.RI "void \fBClearAllBuffers\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetDefaultBuffer\fP (\fBBuffer\fP *buffer)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBID\fP = \fBUniqueIndex\fP()"
.br
.ti -1c
.RI "static bool \fBgenerate_noise\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBModelElement\fP * BPM::Copy () const\fC [virtual]\fP"
Virtual constructor\&. 
.PP
Reimplemented from \fBMonitor\fP\&.
.SS "int BPM::GetIndex () const\fC [virtual]\fP"
Returns the unique index for this class of accelerator components\&. 
.PP
\fBReturns:\fP
.RS 4
An integer containing the unique index for this \fBAcceleratorComponent\fP type\&. 
.RE
.PP

.PP
Reimplemented from \fBMonitor\fP\&.
.SS "const string & BPM::GetType () const\fC [virtual]\fP"
Return the type string for the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the type of the element\&. 
.RE
.PP

.PP
Reimplemented from \fBMonitor\fP\&.
.SS "void BPM::PrepareTracker (\fBComponentTracker\fP & aTracker)\fC [virtual]\fP"
Primary tracking interface\&. Prepares the specified Tracker object for tracking this component\&. 
.PP
\fBParameters:\fP
.RS 4
\fIaTracker\fP The tracker to prepare\&. 
.RE
.PP

.PP
Reimplemented from \fBMonitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
