.TH "BPM::Data" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BPM::Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBct\fP"
.br
.ti -1c
.RI "\fBMeasurement\fP \fBx\fP"
.br
.ti -1c
.RI "\fBMeasurement\fP \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
