.TH "BPM::Buffer" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BPM::Buffer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBPMDataBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBRecord\fP (const \fBBPM\fP &aBPM, const \fBData\fP &data)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
