.TH "BPMChannelCtor" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BPMChannelCtor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBChannelServer::ChannelCtor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBPMChannelCtor\fP (char xy)"
.br
.ti -1c
.RI "virtual \fBROChannel\fP * \fBConstructRO\fP (\fBModelElement\fP *anElement)"
.br
.ti -1c
.RI "virtual \fBRWChannel\fP * \fBConstructRW\fP (\fBModelElement\fP *anElement)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBBPMDataBufferServer\fP \fBtheServer\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
