.TH "CalculateLatticeFunction" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CalculateLatticeFunction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalculateLatticeFunction\fP (double _s, const \fBParticle\fP &_p, \fBRealMatrix\fP &_N)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBLatticeFunction\fP *lfn)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
