.TH "CenteredGeometry" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CenteredGeometry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAcceleratorGeometry\fP\&.
.PP
Inherited by \fBArcGeometry\fP, and \fBRectangularGeometry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCenteredGeometry\fP (double l)"
.br
.ti -1c
.RI "virtual double \fBGetGeometryLength\fP () const"
.br
.ti -1c
.RI "virtual AcceleratorGeometry::Extent \fBGetGeometryExtent\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBCheckBounds\fP (double s1, double s2) const"
.br
.ti -1c
.RI "void \fBCheckBounds\fP (double s) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBlen\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "AcceleratorGeometry::Extent CenteredGeometry::GetGeometryExtent () const\fC [inline]\fP, \fC [virtual]\fP"
Returns the local extent of this geometry\&. 
.PP
\fBReturns:\fP
.RS 4
A pair giving the extent of this geometry\&. 
.RE
.PP

.PP
Implements \fBAcceleratorGeometry\fP\&.
.SS "double CenteredGeometry::GetGeometryLength () const\fC [inline]\fP, \fC [virtual]\fP"
Returns the total arc-length of the geometry\&. 
.PP
\fBReturns:\fP
.RS 4
A double giving the total length of this geometry\&. 
.RE
.PP

.PP
Implements \fBAcceleratorGeometry\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
