.TH "ChannelServer" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChannelServer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChannelCtor\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, \fBChannelCtor\fP * > \fBCtorTable\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBGetROChannels\fP (const string &chID, std::vector< \fBROChannel\fP *> &channels)"
.br
.ti -1c
.RI "size_t \fBGetRWChannels\fP (const string &chID, std::vector< \fBRWChannel\fP *> &channels)"
.br
.ti -1c
.RI "size_t \fBGetROChannels\fP (\fBAcceleratorModel::Beamline\fP &aBeamline, const std::string &chid, std::vector< \fBROChannel\fP *> &channels)"
.br
.ti -1c
.RI "size_t \fBGetRWChannels\fP (\fBAcceleratorModel::Beamline\fP &aBeamline, const std::string &chid, std::vector< \fBRWChannel\fP *> &channels)"
.br
.ti -1c
.RI "void \fBRegisterCtor\fP (\fBChannelCtor\fP *chctor)"
.br
.ti -1c
.RI "void \fBSetRepository\fP (\fBElementRepository\fP *me_repo)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
