.TH "collimatortable" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collimatortable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinrange\fP (double x)"
.br
.ti -1c
.RI "double \fBparabolic\fP (double v1, double v2, double v3, double d)"
.br
.ti -1c
.RI "double \fBinterpolate\fP (double s)"
.br
.ti -1c
.RI "\fBcollimatortable\fP (const char *file, double Gamma=0, double xi=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
