.TH "CollimatorDatabase::FlukaData" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollimatorDatabase::FlukaData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid_coll\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "double \fBposition\fP"
.br
.ti -1c
.RI "double \fBangle\fP"
.br
.ti -1c
.RI "double \fBbeta_x\fP"
.br
.ti -1c
.RI "double \fBbeta_y\fP"
.br
.ti -1c
.RI "double \fBhalf_gap\fP"
.br
.ti -1c
.RI "string \fBmaterial\fP"
.br
.ti -1c
.RI "double \fBlength\fP"
.br
.ti -1c
.RI "double \fBsig_x\fP"
.br
.ti -1c
.RI "double \fBsig_y\fP"
.br
.ti -1c
.RI "double \fBj1_tilt\fP"
.br
.ti -1c
.RI "double \fBj2_tilt\fP"
.br
.ti -1c
.RI "double \fBn_sig\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
