.TH "Collimation::ScatteringModelMerlin" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collimation::ScatteringModelMerlin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScatteringModelsMerlin\&.h>\fP
.PP
Inherits \fBCollimation::ScatteringModelFixed\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Merlin physics model
.PP
\fBScatteringModel\fP preset with Merlin physics model as described in Appleby, R\&.B\&., Barlow, R\&.J\&., Molson, J\&.G\&. et al\&. Eur\&. Phys\&. J\&. C (2016) 76: 520\&. https://dx.doi.org/10.1140/epjc/s10052-016-4363-7 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
