.TH "Collimation::JawImpactData" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collimation::JawImpactData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBturn\fP"
.br
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBxp\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fByp\fP"
.br
.ti -1c
.RI "double \fBct\fP"
.br
.ti -1c
.RI "double \fBdp\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
