.TH "Collimation::ScatteringModelSixTrackSD" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collimation::ScatteringModelSixTrackSD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScatteringModelsMerlin\&.h>\fP
.PP
Inherits \fBCollimation::ScatteringModelFixed\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Sixtrack style physics model + new single diffractive 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
