.TH "Collimation::CrossSections" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collimation::CrossSections
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossSections\fP (\fBMaterial\fP *mat, double E, int scattertype)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCrossSections\fP &rhs)"
.br
.ti -1c
.RI "void \fBConfigureCrossSections\fP (double E0)"
.br
.ti -1c
.RI "double \fBGetTotalMeanFreePath\fP ()"
.br
.ti -1c
.RI "void \fBSet_E0\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_E0\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pN_tot_ref\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pN_tot_ref\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pN_inel_ref\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pN_inel_ref\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_R_ref\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_R_ref\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_R\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_R\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pp_tot\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pp_tot\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pp_el\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pp_el\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pn_el\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pn_el\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pp_sd\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pp_sd\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pn_sd\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pn_sd\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pN_tot\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pN_tot\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pN_inel\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pN_inel\fP () const"
.br
.ti -1c
.RI "void \fBSet_sig_pN_el\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_sig_pN_el\fP () const"
.br
.ti -1c
.RI "void \fBSet_lambda_tot\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_lambda_tot\fP () const"
.br
.ti -1c
.RI "void \fBSet_elastic_diff\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_elastic_diff\fP () const"
.br
.ti -1c
.RI "void \fBSet_com_sqd\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_com_sqd\fP () const"
.br
.ti -1c
.RI "void \fBSet_density\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_density\fP () const"
.br
.ti -1c
.RI "void \fBSet_atomic_mass\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_atomic_mass\fP () const"
.br
.ti -1c
.RI "void \fBSet_atomic_no\fP (double a)"
.br
.ti -1c
.RI "double \fBGet_atomic_no\fP () const"
.br
.ti -1c
.RI "void \fBSet_scat_type\fP (int a)"
.br
.ti -1c
.RI "int \fBGet_scat_type\fP () const"
.br
.ti -1c
.RI "\fBParticleTracking::ppElasticScatter\fP * \fBGetElasticScatter\fP () const"
.br
.ti -1c
.RI "\fBParticleTracking::ppDiffractiveScatter\fP * \fBGetDiffractiveScatter\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
