.TH "CollimatorWakePotentials" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollimatorWakePotentials
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CollimatorWakePotentials\&.h>\fP
.PP
Inherits \fBWakePotentials\fP\&.
.PP
Inherited by \fBResistivePotential\fP, \fBResistiveWakePotentials\fP, \fBResistiveWakePotentials\fP, \fBTaperedCollimatorPotentials\fP, and \fBTaperedCollimatorPotentials\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollimatorWakePotentials\fP (int m, double rad=0, double conduct=0)"
.br
.ti -1c
.RI "virtual double \fBWlong\fP (double s, int m) const =0"
.br
.ti -1c
.RI "virtual double \fBWtrans\fP (double s, int m) const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBnmodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract class for calculating the longitudinal and transverse single-bunch wakefield potentials (Greens functions) with modes 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
