.TH "ComponentIntegrator" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentIntegrator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDefaultMarkerIntegrator\fP, and \fBTBunchCMPTracker< _B >::B_Integrator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTrackAll\fP ()"
.br
.ti -1c
.RI "virtual double \fBTrack\fP (double ds)"
.br
.ti -1c
.RI "virtual int \fBGetComponentIndex\fP () const =0"
.br
.ti -1c
.RI "double \fBGetIntegratedLength\fP () const"
.br
.ti -1c
.RI "double \fBGetRemainingLength\fP () const"
.br
.ti -1c
.RI "bool \fBIsValidStep\fP (double ds) const"
.br
.ti -1c
.RI "virtual \fBFloatRange\fP \fBGetValidStepRange\fP () const"
.br
.ti -1c
.RI "bool \fBAtEntrance\fP () const"
.br
.ti -1c
.RI "bool \fBAtExit\fP (double step=0) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &aComponent)"
.br
.ti -1c
.RI "virtual void \fBTrackStep\fP (double ds)=0"
.br
.ti -1c
.RI "virtual void \fBTrackEntrance\fP ()"
.br
.ti -1c
.RI "virtual void \fBTrackExit\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBComponentTracker\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
