.TH "ComponentTracker::IntegratorSet" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentTracker::IntegratorSet
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::map< int, \fBComponentIntegrator\fP *> \fBIMap\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBAdd\fP (\fBComponentIntegrator\fP *intg)"
.br
.ti -1c
.RI "\fBComponentIntegrator\fP * \fBGetIntegrator\fP (int n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
