.TH "ComponentFrame" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentFrame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLatticeFrame\fP\&.
.PP
Inherited by \fBPatchFrame\fP, and \fBTComponentFrame< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentFrame\fP (\fBAcceleratorComponent\fP &ac, const string &\fBid\fP='')"
.br
.ti -1c
.RI "\fBComponentFrame\fP (const \fBComponentFrame\fP &rhs)"
.br
.ti -1c
.RI "\fBAcceleratorComponent\fP & \fBGetComponent\fP ()"
.br
.ti -1c
.RI "const \fBAcceleratorComponent\fP & \fBGetComponent\fP () const"
.br
.ti -1c
.RI "bool \fBIsComponent\fP () const"
.br
.ti -1c
.RI "virtual const \fBTransform3D\fP * \fBGetEntranceGeometryPatch\fP () const"
.br
.ti -1c
.RI "virtual const \fBTransform3D\fP * \fBGetExitGeometryPatch\fP () const"
.br
.ti -1c
.RI "virtual void \fBInvalidate\fP () const"
.br
.ti -1c
.RI "virtual const string & \fBGetName\fP () const"
.br
.ti -1c
.RI "virtual const string & \fBGetType\fP () const"
.br
.ti -1c
.RI "virtual \fBModelElement\fP * \fBCopy\fP () const"
.br
.ti -1c
.RI "void \fBSetBeamlineIndex\fP (size_t n)"
.br
.ti -1c
.RI "size_t \fBGetBeamlineIndex\fP () const"
.br
.ti -1c
.RI "void \fBAppendBeamlineIndecies\fP (std::vector< size_t > &) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentFrame\fP (\fBAcceleratorComponent\fP *ac, const string &\fBid\fP='')"
.br
.ti -1c
.RI "virtual bool \fBIsBoundaryPlane\fP (\fBBoundaryPlane\fP p, const \fBLatticeFrame\fP *aSubFrame) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAcceleratorComponent\fP * \fBtheComponent\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBModelElement\fP * ComponentFrame::Copy () const\fC [virtual]\fP"
Virtual constructor\&. 
.PP
Implements \fBModelElement\fP\&.
.PP
Reimplemented in \fBPatchFrame\fP, and \fBTComponentFrame< T >\fP\&.
.SS "const string & ComponentFrame::GetName () const\fC [inline]\fP, \fC [virtual]\fP"
Return the name of the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the name of the element\&. 
.RE
.PP

.PP
Reimplemented from \fBModelElement\fP\&.
.PP
Reimplemented in \fBPatchFrame\fP\&.
.SS "const string & ComponentFrame::GetType () const\fC [virtual]\fP"
Return the type string for the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the type of the element\&. 
.RE
.PP

.PP
Implements \fBModelElement\fP\&.
.PP
Reimplemented in \fBPatchFrame\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
