.TH "CompositeMaterial" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompositeMaterial
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaterial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBCalculateElectronDensity\fP ()"
.br
.ti -1c
.RI "double \fBCalculatePlasmaEnergy\fP ()"
.br
.ti -1c
.RI "double \fBCalculateMeanExcitationEnergy\fP ()"
.br
.ti -1c
.RI "double \fBCalculateRadiationLength\fP ()"
.br
.ti -1c
.RI "double \fBCalculateSixtrackdEdx\fP ()"
.br
.ti -1c
.RI "void \fBCalculateAllWeightedVariables\fP ()"
.br
.ti -1c
.RI "double \fBCalculateWeightedA\fP ()"
.br
.ti -1c
.RI "double \fBCalculateWeightedZ\fP ()"
.br
.ti -1c
.RI "double \fBCalculateSixTrackElasticNucleusCrossSection\fP ()"
.br
.ti -1c
.RI "void \fBSetName\fP (std::string)"
.br
.ti -1c
.RI "void \fBSetSymbol\fP (std::string)"
.br
.ti -1c
.RI "void \fBSetConductivity\fP (double)"
.br
.ti -1c
.RI "void \fBSetRadiationLength\fP (double)"
.br
.ti -1c
.RI "void \fBSetDensity\fP (double)"
.br
.ti -1c
.RI "void \fBSetElectronDensity\fP (double)"
.br
.ti -1c
.RI "void \fBSetMeanExcitationEnergy\fP (double)"
.br
.ti -1c
.RI "void \fBSetPlasmaEnergy\fP (double)"
.br
.ti -1c
.RI "void \fBSetSixtrackdEdx\fP (double)"
.br
.ti -1c
.RI "double \fBGetAtomicNumber\fP () const"
.br
.ti -1c
.RI "string \fBGetName\fP () const"
.br
.ti -1c
.RI "string \fBGetSymbol\fP () const"
.br
.ti -1c
.RI "double \fBGetAtomicMass\fP () const"
.br
.ti -1c
.RI "double \fBGetConductivity\fP () const"
.br
.ti -1c
.RI "double \fBGetRadiationLength\fP () const"
.br
.ti -1c
.RI "double \fBGetRadiationLengthInM\fP () const"
.br
.ti -1c
.RI "double \fBGetDensity\fP () const"
.br
.ti -1c
.RI "double \fBGetElectronDensity\fP () const"
.br
.ti -1c
.RI "double \fBGetMeanExcitationEnergy\fP () const"
.br
.ti -1c
.RI "double \fBGetPlasmaEnergy\fP () const"
.br
.ti -1c
.RI "double \fBGetSixtrackTotalNucleusCrossSection\fP () const"
.br
.ti -1c
.RI "double \fBGetSixtrackInelasticNucleusCrossSection\fP () const"
.br
.ti -1c
.RI "double \fBGetSixtrackRutherfordCrossSection\fP () const"
.br
.ti -1c
.RI "double \fBGetSixtrackdEdx\fP () const"
.br
.ti -1c
.RI "double \fBGetSixtrackNuclearSlope\fP () const"
.br
.ti -1c
.RI "bool \fBVerifyMaterial\fP () const"
.br
.ti -1c
.RI "bool \fBAddMaterialByMassFraction\fP (\fBMaterial\fP *, double)"
.br
.ti -1c
.RI "bool \fBAddMaterialByNumberFraction\fP (\fBMaterial\fP *, double)"
.br
.ti -1c
.RI "\fBMaterial\fP * \fBSelectRandomMaterial\fP ()"
.br
.ti -1c
.RI "\fBMaterial\fP * \fBGetCurrentMaterial\fP ()"
.br
.ti -1c
.RI "bool \fBAssemble\fP ()"
.br
.ti -1c
.RI "bool \fBIsAssembled\fP ()"
.br
.ti -1c
.RI "virtual bool \fBIsMixture\fP () const"
.br
.ti -1c
.RI "vector< pair< string, double > > \fBGetConstituentElements\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
