.TH "ComponentDivider" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentDivider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponentStepper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentDivider\fP (int ns, double min_step=0)"
.br
.ti -1c
.RI "virtual void \fBSetComponent\fP (\fBAcceleratorComponent\fP &cmp)"
.br
.ti -1c
.RI "virtual bool \fBIncrement\fP (double ds)"
.br
.ti -1c
.RI "virtual double \fBDistanceToStepBoundary\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
