.TH "Dispersion" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dispersion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDispersion\fP (\fBAcceleratorModel\fP *aModel, double refMomentum)"
.br
.ti -1c
.RI "void \fBFindDispersion\fP (int n=0)"
.br
.ti -1c
.RI "void \fBFindRMSDispersion\fP (ofstream *file=nullptr)"
.br
.ti -1c
.RI "double \fBSetDelta\fP (double new_delta)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBDx\fP"
.br
.ti -1c
.RI "double \fBDxp\fP"
.br
.ti -1c
.RI "double \fBDy\fP"
.br
.ti -1c
.RI "double \fBDyp\fP"
.br
.ti -1c
.RI "double \fBDxRMS\fP"
.br
.ti -1c
.RI "double \fBDyRMS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
