.TH "EquilibriumDistribution" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EquilibriumDistribution
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEquilibriumDistribution\fP (\fBAcceleratorModel\fP *aModel, double refMomentum)"
.br
.ti -1c
.RI "double \fBEmittance\fP (int n)"
.br
.ti -1c
.RI "double \fBDampingTime\fP (int n)"
.br
.ti -1c
.RI "double \fBDampingConstant\fP (int n)"
.br
.ti -1c
.RI "double \fBTune\fP (int n)"
.br
.ti -1c
.RI "double \fBSynchronousTime\fP ()"
.br
.ti -1c
.RI "double \fBBeamMoment\fP (int i, int j, int ncpt=0)"
.br
.ti -1c
.RI "void \fBCalculateDampingConstants\fP ()"
.br
.ti -1c
.RI "void \fBCalculateEmittance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
