.TH "FrameModifier" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameModifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLatticeFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrameModifier\fP (\fBLatticeFrame\fP *frame, const std::string &label='')"
.br
.ti -1c
.RI "\fBModelElement\fP * \fBCopy\fP () const"
.br
.ti -1c
.RI "const string & \fBGetType\fP () const"
.br
.ti -1c
.RI "virtual void \fBInvalidate\fP () const"
.br
.ti -1c
.RI "virtual void \fBConsolidateConstruction\fP ()"
.br
.ti -1c
.RI "void \fBRemove\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBModelElement\fP * FrameModifier::Copy () const\fC [virtual]\fP"
Virtual constructor\&. 
.PP
Implements \fBModelElement\fP\&.
.SS "const string & FrameModifier::GetType () const\fC [virtual]\fP"
Return the type string for the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the type of the element\&. 
.RE
.PP

.PP
Implements \fBModelElement\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
