.TH "GeneralRotation" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneralRotation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRot3Drep\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneralRotation\fP (const \fBGeneralRotation\fP &gr)"
.br
.ti -1c
.RI "\fBGeneralRotation\fP (const \fBRealMatrix\fP &r)"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBinv\fP () const"
.br
.ti -1c
.RI "virtual \fBPoint3D\fP \fBrotate\fP (const \fBPoint3D\fP &p) const"
.br
.ti -1c
.RI "virtual \fBVector3D\fP \fBrotate\fP (const \fBVector3D\fP &v) const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBdot\fP (const \fBRot3Drep\fP &r) const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBdotBy\fP (const \fBRotationX\fP &rx) const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBdotBy\fP (const \fBRotationY\fP &ry) const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBdotBy\fP (const \fBRotationZ\fP &rz) const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBdotBy\fP (const \fBGeneralRotation\fP &r) const"
.br
.ti -1c
.RI "virtual RotationType \fBtype\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisIdentity\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisXrot\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisYrot\fP () const"
.br
.ti -1c
.RI "virtual bool \fBisZrot\fP () const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBrotXbyPI\fP () const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBrotYbyPI\fP () const"
.br
.ti -1c
.RI "virtual \fBRot3Drep\fP * \fBrotZbyPI\fP () const"
.br
.ti -1c
.RI "virtual \fBRealMatrix\fP & \fBgetMatrix\fP (\fBRealMatrix\fP &m) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRotationX\fP"
.br
.ti -1c
.RI "class \fBRotationY\fP"
.br
.ti -1c
.RI "class \fBRotationZ\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
