.TH "GirderMount" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GirderMount
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSupportStructure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGirderMount\fP (const std::string &\fBid\fP)"
.br
.ti -1c
.RI "virtual const string & \fBGetType\fP () const"
.br
.ti -1c
.RI "virtual \fBModelElement\fP * \fBCopy\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBModelElement\fP * GirderMount::Copy () const\fC [virtual]\fP"
Virtual constructor\&. 
.PP
Reimplemented from \fBSequenceFrame\fP\&.
.SS "const string & GirderMount::GetType () const\fC [virtual]\fP"
Return the type string for the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the type of the element\&. 
.RE
.PP

.PP
Reimplemented from \fBSequenceFrame\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
