.TH "InterpolatedAperture::ap" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterpolatedAperture::ap
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBs\fP"
.br
.ti -1c
.RI "double \fBap1\fP"
.br
.ti -1c
.RI "double \fBap2\fP"
.br
.ti -1c
.RI "double \fBap3\fP"
.br
.ti -1c
.RI "double \fBap4\fP"
.br
.ti -1c
.RI "\fBApertureClass_t\fP \fBApType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
