.TH "LatticeFrame" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LatticeFrame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModelElement\fP, and \fBTransformable\fP\&.
.PP
Inherited by \fBComponentFrame\fP, \fBFrameModifier\fP, and \fBSequenceFrame\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBAcceleratorGeometry::BoundaryPlane\fP \fBBoundaryPlane\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLatticeFrame\fP (const string &\fBid\fP='')"
.br
.ti -1c
.RI "\fBLatticeFrame\fP (const \fBLatticeFrame\fP &rhs)"
.br
.ti -1c
.RI "virtual \fBTransform3D\fP \fBGetFrameTransform\fP (const \fBLatticeFrame\fP *sframe=GLOBAL_FRAME) const"
.br
.ti -1c
.RI "virtual \fBTransform3D\fP \fBGetLocalFrameTransform\fP () const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetPhysicalTransform\fP (const \fBLatticeFrame\fP *sframe=GLOBAL_FRAME) const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetLocalPhysicalTransform\fP () const"
.br
.ti -1c
.RI "const \fBAcceleratorGeometry\fP * \fBGetGeometry\fP () const"
.br
.ti -1c
.RI "double \fBGetPosition\fP (const \fBLatticeFrame\fP *sframe=GLOBAL_FRAME) const"
.br
.ti -1c
.RI "double \fBGetLocalPosition\fP () const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetGeometryTransform\fP (double s0, double s) const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetGeometryTransform\fP (double s) const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetGeometryTransform\fP (\fBBoundaryPlane\fP p) const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetTotalGeometryTransform\fP () const"
.br
.ti -1c
.RI "AcceleratorGeometry::Extent \fBGetGeometryExtent\fP (const \fBLatticeFrame\fP *sframe=GLOBAL_FRAME) const"
.br
.ti -1c
.RI "AcceleratorGeometry::Extent \fBGetLocalGeometryExtent\fP () const"
.br
.ti -1c
.RI "double \fBGetGeometryLength\fP () const"
.br
.ti -1c
.RI "virtual \fBTransform3D\fP \fBGetBoundaryPlaneTransform\fP (\fBBoundaryPlane\fP p) const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetEntrancePlaneTransform\fP () const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBGetExitPlaneTransform\fP () const"
.br
.ti -1c
.RI "void \fBApplyLocalFrameTransform\fP (const \fBTransform3D\fP &t1)"
.br
.ti -1c
.RI "void \fBSetLocalFrameTransform\fP (const \fBTransform3D\fP &t)"
.br
.ti -1c
.RI "void \fBClearLocalFrameTransform\fP ()"
.br
.ti -1c
.RI "virtual void \fBConsolidateConstruction\fP ()"
.br
.ti -1c
.RI "void \fBSetLocalPosition\fP (double s)"
.br
.ti -1c
.RI "\fBLatticeFrame\fP * \fBSetSuperFrame\fP (\fBLatticeFrame\fP *aFrame)"
.br
.ti -1c
.RI "virtual bool \fBReplaceSubFrame\fP (\fBLatticeFrame\fP *subFrame, \fBLatticeFrame\fP *newSubFrame)"
.br
.ti -1c
.RI "bool \fBIsGlobalFrame\fP () const"
.br
.ti -1c
.RI "\fBLatticeFrame\fP * \fBGetGlobalFrame\fP () const"
.br
.ti -1c
.RI "virtual void \fBTraverse\fP (\fBFrameTraverser\fP &ft)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetGeometry\fP (const \fBAcceleratorGeometry\fP *geom)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLatticeFrame\fP * \fBsuperFrame\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
