.TH "MADKeyMap" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MADKeyMap
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbad_key\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, size_t > \fBkey_map\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMADKeyMap\fP (const std::string &hstr)"
.br
.ti -1c
.RI "virtual double \fBGetParameter\fP (const std::string &key, bool warn=true)"
.br
.ti -1c
.RI "virtual void \fBReadRow\fP (std::istream &is)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhas_type\fP"
.br
.ti -1c
.RI "bool \fBhas_apertype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
