.TH "map_applicator< M, X >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_applicator< M, X >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmap_applicator\fP (const M &anM)"
.br
.ti -1c
.RI "void \fBoperator()\fP (X &x) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const M & \fBm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class M, class X>
.br
struct map_applicator< M, X >"
Functor for applying a map as given 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
