.TH "MaterialDatabase" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialDatabase
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP * \fBFindMaterial\fP (std::string symbol)"
.br
.ti -1c
.RI "bool \fBVerifyMaterials\fP ()"
.br
.ti -1c
.RI "void \fBDumpMaterialProperties\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, \fBMaterial\fP * > \fBdb\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
