.TH "MerlinIO" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MerlinIO
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::istream & \fBin\fP ()"
.br
.ti -1c
.RI "static std::ostream & \fBout\fP ()"
.br
.ti -1c
.RI "static std::ostream & \fBerror\fP ()"
.br
.ti -1c
.RI "static std::ostream & \fBwarning\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::istream * \fBstd_in\fP = &std::cin"
.br
.ti -1c
.RI "static std::ostream * \fBstd_out\fP = &std::cout"
.br
.ti -1c
.RI "static std::ostream * \fBstd_err\fP = &std::cerr"
.br
.ti -1c
.RI "static std::ostream * \fBstd_warn\fP = &std::cerr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
