.TH "MerlinProfile" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MerlinProfile
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddProcess\fP (std::string ID)"
.br
.ti -1c
.RI "static void \fBRemoveProcess\fP (std::string ID)"
.br
.ti -1c
.RI "static void \fBStartProcessTimer\fP (std::string ID)"
.br
.ti -1c
.RI "static void \fBEndProcessTimer\fP (std::string ID)"
.br
.ti -1c
.RI "static void \fBSetProcessDuration\fP (timespec t, std::string ID)"
.br
.ti -1c
.RI "static void \fBClearTime\fP ()"
.br
.ti -1c
.RI "static void \fBGetProfileData\fP ()"
.br
.ti -1c
.RI "static bool \fBIsEnabled\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
