.TH "MerlinException" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MerlinException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MerlinException\&.h>\fP
.PP
Inherited by \fBAcceleratorModel::BadRange\fP, \fBInterpolation::BadRange\fP, and \fBParticleTracking::ExcessiveParticleLoss\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMerlinException\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBMerlinException\fP ()"
.br
.ti -1c
.RI "virtual \fB~MerlinException\fP ()"
.br
.ti -1c
.RI "const char * \fBMsg\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetMsg\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBAppendMsg\fP (const std::string &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Root class for all Merlin exceptions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MerlinException::MerlinException (const std::string & s)\fC [inline]\fP, \fC [explicit]\fP"
Constructor: Builds the \fBMerlinException\fP and sets the exception message\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP The exception message\&. 
.RE
.PP

.SS "MerlinException::MerlinException ()\fC [inline]\fP"
Constructor: Builds the \fBMerlinException\fP\&. 
.SS "virtual MerlinException::~MerlinException ()\fC [inline]\fP, \fC [virtual]\fP"
Virtual destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void MerlinException::AppendMsg (const std::string & s)\fC [inline]\fP, \fC [protected]\fP"
Appends a string to the exception message\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSetMsg\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIs\fP The string to append to the exception message\&. 
.RE
.PP

.SS "const char * MerlinException::Msg () const\fC [inline]\fP"
Gets the exception message\&. 
.PP
\fBReturns:\fP
.RS 4
The current exception message\&. 
.RE
.PP

.SS "void MerlinException::SetMsg (const std::string & s)\fC [inline]\fP, \fC [protected]\fP"
Sets the exception message\&. 
.PP
\fBSee also:\fP
.RS 4
\fBAppendMsg\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIs\fP The exception message\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
