.TH "MLCG" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MLCG
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRNG\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMLCG\fP (_G_int32_t seed1=0, _G_int32_t seed2=1)"
.br
.ti -1c
.RI "virtual _G_uint32_t \fBasLong\fP ()"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.ti -1c
.RI "_G_int32_t \fBseed1\fP ()"
.br
.ti -1c
.RI "void \fBseed1\fP (_G_int32_t)"
.br
.ti -1c
.RI "_G_int32_t \fBseed2\fP ()"
.br
.ti -1c
.RI "void \fBseed2\fP (_G_int32_t)"
.br
.ti -1c
.RI "void \fBreseed\fP (_G_int32_t, _G_int32_t)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
