.TH "ModelElement" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelElement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ModelElement\&.h>\fP
.PP
Inherited by \fBAcceleratorComponent\fP, \fBCorrectorWinding\fP, \fBKlystron\fP, and \fBLatticeFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelElement\fP (const std::string &aName='<UNNAMED>')"
.br
.ti -1c
.RI "virtual const std::string & \fBGetName\fP () const"
.br
.ti -1c
.RI "virtual const std::string & \fBGetType\fP () const =0"
.br
.ti -1c
.RI "std::string \fBGetQualifiedName\fP () const"
.br
.ti -1c
.RI "virtual \fBModelElement\fP * \fBCopy\fP () const =0"
.br
.ti -1c
.RI "void \fBSetName\fP (const std::string &name)"
.br
.ti -1c
.RI "size_t \fBGetBeamlineIndecies\fP (std::vector< size_t > &ivec) const"
.br
.ti -1c
.RI "virtual void \fBAppendBeamlineIndecies\fP (std::vector< size_t > &ivec) const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (const std::string &aName)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Root class for all elements/components which are used to construct an \fBAcceleratorModel\fP\&. All \fBModelElement\fP objects are characterised by a type string and an identifier (name)\&. The type string identifies the type of element (class), while the name is specific to an instance of that element type\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ModelElement::ModelElement (const std::string & aName = \fC'<UNNAMED>'\fP)\fC [inline]\fP, \fC [explicit]\fP"
Constructor taking the name of the element\&. 
.PP
\fBParameters:\fP
.RS 4
\fIaName\fP A string containing the name of the element 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBModelElement\fP* ModelElement::Copy () const\fC [pure virtual]\fP"
Virtual constructor\&. 
.PP
Implemented in \fBDecapole\fP, \fBSkewSextupole\fP, \fBOctupole\fP, \fBSectorBend\fP, \fBSkewQuadrupole\fP, \fBBPM\fP, \fBSimpleMount\fP, \fBSextupole\fP, \fBRMSProfileMonitor\fP, \fBGirderMount\fP, \fBMonitor\fP, \fBCollimator\fP, \fBKlystron\fP, \fBComponentFrame\fP, \fBQuadrupole\fP, \fBMagnetMover\fP, \fBSolenoid\fP, \fBSequenceFrame\fP, \fBParticleTracking::ParticleMapComponent\fP, \fBYCor\fP, \fBTransverseRFStructure\fP, \fBPatchFrame\fP, \fBDrift\fP, \fBTWRFStructure\fP, \fBHollowElectronLens\fP, \fBCrabMarker\fP, \fBMarker\fP, \fBSWRFStructure\fP, \fBCorrectorWinding\fP, \fBTComponentFrame< T >\fP, \fBFrameModifier\fP, and \fBXCor\fP\&.
.SS "size_t ModelElement::GetBeamlineIndecies (std::vector< size_t > & ivec) const\fC [inline]\fP"
Returns in ivec an ordered list of beamline indecies associated with this \fBModelElement\fP\&. Returns the length of ivec\&. 
.PP
\fBParameters:\fP
.RS 4
\fIivec\fP The ordered list of beamline indecies associated with this \fBModelElement\fP\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The size of ivec 
.RE
.PP

.SS "const std::string & ModelElement::GetName () const\fC [inline]\fP, \fC [virtual]\fP"
Return the name of the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the name of the element\&. 
.RE
.PP

.PP
Reimplemented in \fBComponentFrame\fP, \fBPatchFrame\fP, and \fBCorrectorWinding\fP\&.
.SS "std::string ModelElement::GetQualifiedName () const\fC [inline]\fP"
Return the qualified name of the component\&. The qualified name has the form typestr\&.namestr\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the qualified name of the element\&. 
.RE
.PP

.SS "virtual const std::string& ModelElement::GetType () const\fC [pure virtual]\fP"
Return the type string for the element\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the type of the element\&. 
.RE
.PP

.PP
Implemented in \fBDecapole\fP, \fBSkewSextupole\fP, \fBOctupole\fP, \fBSectorBend\fP, \fBSkewQuadrupole\fP, \fBBPM\fP, \fBSimpleMount\fP, \fBSextupole\fP, \fBRMSProfileMonitor\fP, \fBGirderMount\fP, \fBMonitor\fP, \fBSequenceFrame\fP, \fBKlystron\fP, \fBQuadrupole\fP, \fBComponentFrame\fP, \fBCollimator\fP, \fBYCor\fP, \fBMagnetMover\fP, \fBSolenoid\fP, \fBParticleTracking::ParticleMapComponent\fP, \fBMarker\fP, \fBXCor\fP, \fBCorrectorWinding\fP, \fBPatchFrame\fP, \fBFrameModifier\fP, \fBTransverseRFStructure\fP, \fBDrift\fP, \fBTWRFStructure\fP, \fBHollowElectronLens\fP, \fBCrabMarker\fP, and \fBSWRFStructure\fP\&.
.SS "void ModelElement::Init (const std::string & aName)\fC [inline]\fP, \fC [protected]\fP"
Initialise the \fBModelElement\fP with the specified name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIaName\fP A string containing the element name\&. 
.RE
.PP

.SS "void ModelElement::SetName (const std::string & name)\fC [inline]\fP"
Set the name of the component\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP A string containing the element name\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "std::string ModelElement::id\fC [protected]\fP"
The name of the element\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
