.TH "MultiNormal< N >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiNormal< N >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiNormal\fP (const \fBRealMatrix\fP &Cov, const \fBRealVector\fP &M)"
.br
.ti -1c
.RI "\fBMultiNormal\fP (const \fBTCovMtrx\fP< double, N > &Cov, const \fBRealVector\fP &M)"
.br
.ti -1c
.RI "\fBMultiNormal\fP (const \fBTPSMoments\fP< N/2 > &pm)"
.br
.ti -1c
.RI "\fBRealVector\fP \fBGetRandVec\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
