.TH "MVCMatrix< T, N >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MVCMatrix< T, N >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBmean\fP (int n) const"
.br
.ti -1c
.RI "T \fBstd\fP (int n) const"
.br
.ti -1c
.RI "T \fBvariance\fP (int n) const"
.br
.ti -1c
.RI "T \fBr\fP (int n, int m) const"
.br
.ti -1c
.RI "T & \fBoperator()\fP (int i, int j)"
.br
.ti -1c
.RI "const T & \fBoperator()\fP (int i, int j) const"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int n)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int n) const"
.br
.ti -1c
.RI "void \fBzero\fP ()"
.br
.ti -1c
.RI "void \fBprintFormatted\fP (ostream &os, bool normalised=true) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMVCMatrix\fP< T, N > &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBMVCMatrix\fP< T, N > &rhs) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
