.TH "NumericalRange< T, C >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumericalRange< T, C >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRangeBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNumericalRange\fP (const T &lo, const T &hi)"
.br
.ti -1c
.RI "\fBNumericalRange\fP (\fBUnboundedRange\fP)"
.br
.ti -1c
.RI "\fBNumericalRange\fP (const T &fp)"
.br
.ti -1c
.RI "bool \fBIsUnbounded\fP () const"
.br
.ti -1c
.RI "bool \fBIsFixedPoint\fP () const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const T &x) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNumericalRange\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBNumericalRange\fP &rhs) const"
.br
.ti -1c
.RI "RangeBase::Result \fBCheck\fP (const T &x) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBlower\fP"
.br
.ti -1c
.RI "T \fBupper\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
