.TH "ParticleTracking::LossMapCollimationOutput" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::LossMapCollimationOutput
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBParticleTracking::CollimationOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLossMapCollimationOutput\fP (OutputType otype=tencm)"
.br
.ti -1c
.RI "virtual void \fBFinalise\fP ()"
.br
.ti -1c
.RI "virtual void \fBOutput\fP (std::ostream *os)"
.br
.ti -1c
.RI "virtual void \fBDispose\fP (\fBAcceleratorComponent\fP &currcomponent, double pos, \fBParticle\fP &particle, int turn=0)"
.br
.ti -1c
.RI "void \fBSetWarmRegion\fP (std::pair< double, double > wr)"
.br
.ti -1c
.RI "void \fBClearWarmRegions\fP ()"
.br
.ti -1c
.RI "std::vector< std::pair< double, double > > \fBGetWarmRegions\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::pair< double, double > > \fBWarmRegions\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void ParticleTracking::LossMapCollimationOutput::ClearWarmRegions ()"
Clears out any previously defined warm regions\&. 
.SS "void ParticleTracking::LossMapCollimationOutput::Dispose (\fBAcceleratorComponent\fP & currcomponent, double pos, \fBParticle\fP & particle, int turn = \fC0\fP)\fC [virtual]\fP"
Called from CollimateProtonProcess::DoScatter to add a particle to the \fBCollimationOutput\fP 
.PP
Reimplemented from \fBParticleTracking::CollimationOutput\fP\&.
.SS "void ParticleTracking::LossMapCollimationOutput::Finalise ()\fC [virtual]\fP"
Finalise will call any sorting algorithms and perform formatting for final output 
.PP
Reimplemented from \fBParticleTracking::CollimationOutput\fP\&.
.SS "std::vector< std::pair< double, double > > ParticleTracking::LossMapCollimationOutput::GetWarmRegions () const"
Gets the vector containing the currently set warm regions of the machine\&. 
.PP
\fBReturns:\fP
.RS 4
The std::vector of std::pair<double,double> with each entry containing the start and end locations of warm regions\&. 
.RE
.PP

.SS "void ParticleTracking::LossMapCollimationOutput::Output (std::ostream * os)\fC [virtual]\fP"
Outputs the loss map data to a specified output stream 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP The stream to output to\&. 
.RE
.PP

.PP
Reimplemented from \fBParticleTracking::CollimationOutput\fP\&.
.SS "void ParticleTracking::LossMapCollimationOutput::SetWarmRegion (std::pair< double, double > wr)"
Sets a warm area of the machine\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwr\fP A std::pair that contains the start and end location of a warm region\&. First contains the start location, and second the end\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
