.TH "ParticleTracking::ElectronBunch" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::ElectronBunch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBParticleTracking::ParticleBunch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElectronBunch\fP (double P0, double \fBQ\fP, PSvectorArray &particles)"
.br
.ti -1c
.RI "\fBElectronBunch\fP (double P0, double \fBQ\fP, std::istream &is)"
.br
.ti -1c
.RI "\fBElectronBunch\fP (double P0, double Qm=1)"
.br
.ti -1c
.RI "virtual bool \fBIsStable\fP () const"
.br
.ti -1c
.RI "virtual double \fBGetParticleMass\fP () const"
.br
.ti -1c
.RI "virtual double \fBGetParticleMassMeV\fP () const"
.br
.ti -1c
.RI "virtual double \fBGetParticleLifetime\fP () const"
.br
.ti -1c
.RI "void \fBset\fP ()"
.br
.ti -1c
.RI "void \fBreport\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
