.TH "ParticleTracking::HollowELensProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::HollowELensProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTBunchProc< B >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHollowELensProcess\fP (int priority)"
.br
.ti -1c
.RI "virtual void \fBInitialiseProcess\fP (\fBBunch\fP &bunch)"
.br
.ti -1c
.RI "virtual void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &component)"
.br
.ti -1c
.RI "virtual void \fBDoProcess\fP (double ds)"
.br
.ti -1c
.RI "virtual double \fBGetMaxAllowedStepSize\fP () const"
.br
.ti -1c
.RI "virtual double \fBCalcThetaMax\fP (double r)"
.br
.ti -1c
.RI "virtual double \fBCalcKickSimple\fP (\fBParticle\fP &p)"
.br
.ti -1c
.RI "virtual double \fBCalcKickSimple\fP (double R)"
.br
.ti -1c
.RI "virtual double \fBCalcKickRadial\fP (\fBParticle\fP &p)"
.br
.ti -1c
.RI "virtual double \fBCalcKickRadial\fP (double R)"
.br
.ti -1c
.RI "virtual void \fBOutputProfile\fP (std::ostream *os, double E=7000, double min=0, double max=10)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
