.TH "ParticleTracking::RingDeltaTProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::RingDeltaTProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTBunchProc< B >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingDeltaTProcess\fP (int prio)"
.br
.ti -1c
.RI "virtual void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &component)"
.br
.ti -1c
.RI "virtual void \fBDoProcess\fP (double ds)"
.br
.ti -1c
.RI "virtual double \fBGetMaxAllowedStepSize\fP () const"
.br
.ti -1c
.RI "void \fBSetBendScale\fP (double bendscale)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
