.TH "ParticleTracking::CollimateProtonProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::CollimateProtonProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBParticleTracking::CollimateParticleProcess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollimateProtonProcess\fP (int priority, int mode, std::ostream *osp=nullptr)"
.br
.ti -1c
.RI "void \fBSetScatteringModel\fP (\fBCollimation::ScatteringModel\fP *s)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParticleTracking::CollimateProtonProcess::CollimateProtonProcess (int priority, int mode, std::ostream * osp = \fCnullptr\fP)"
Constructor taking the collimation mode, and the output stream pointer to which to print the results\&. mode can be a logical OR combination of the collimation modes\&. A null pointer for osp (default) suppresses output\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
