.TH "ParticleTracking::NANCheckProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::NANCheckProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTBunchProc< B >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNANCheckProcess\fP (const string &aID='NAN Check', int prio=0)"
.br
.ti -1c
.RI "void \fBInitialiseProcess\fP (\fBBunch\fP &bunch)"
.br
.ti -1c
.RI "void \fBDoProcess\fP (const double ds)"
.br
.ti -1c
.RI "double \fBGetMaxAllowedStepSize\fP () const"
.br
.ti -1c
.RI "void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &component)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
