.TH "ParticleTracking::ppDiffractiveScatter" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::ppDiffractiveScatter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DiffractiveScatter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBppDiffractiveScatter\fP ()"
.br
.ti -1c
.RI "void \fBGenerateDistribution\fP (double energy)"
.br
.ti -1c
.RI "void \fBGenerateDsigDtDxi\fP (double energy)"
.br
.ti -1c
.RI "void \fBIntegrateDsigDtDxi\fP ()"
.br
.ti -1c
.RI "double \fBSelectT\fP ()"
.br
.RI "Picks a t value from the generated distribution (including interpolation) "
.ti -1c
.RI "double \fBSelectXi\fP ()"
.br
.RI "Picks an Xi value from the generated distribution (including interpolation) "
.ti -1c
.RI "void \fBSetTMin\fP (double tmin)"
.br
.ti -1c
.RI "void \fBSetTMax\fP (double tmax)"
.br
.ti -1c
.RI "void \fBSetXiMax\fP (double ximax)"
.br
.ti -1c
.RI "void \fBSetXiMin\fP (double ximin)"
.br
.ti -1c
.RI "void \fBSetTStepSize\fP (double step)"
.br
.ti -1c
.RI "void \fBSetXiStepSize\fP (double step)"
.br
.ti -1c
.RI "double \fBGetTMin\fP () const"
.br
.ti -1c
.RI "double \fBGetTMax\fP () const"
.br
.ti -1c
.RI "double \fBGetXiMin\fP () const"
.br
.ti -1c
.RI "double \fBGetXiMax\fP () const"
.br
.ti -1c
.RI "double \fBGetTStepSize\fP () const"
.br
.ti -1c
.RI "double \fBGetXiStepSize\fP () const"
.br
.ti -1c
.RI "double \fBGetDiffractiveCrossSection\fP () const"
.br
.ti -1c
.RI "void \fBEnableDebug\fP (bool debug)"
.br
.ti -1c
.RI "std::pair< double, double > \fBSelect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for all things relating to proton-proton single diffractive scattering\&. This includes:
.IP "\(bu" 2
Generation of differential cross sections\&.
.IP "\(bu" 2
Integration of the differential cross sections\&.
.IP "\(bu" 2
Generation of momentum transfer t values for calculation of scattering angles\&.
.IP "\(bu" 2
Generation of mass loss values for calculation of momentum changes\&.
.IP "\(bu" 2
Multiple scattering models 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParticleTracking::ppDiffractiveScatter::ppDiffractiveScatter ()\fC [inline]\fP"
class constructor 
.SH "Member Function Documentation"
.PP 
.SS "void ParticleTracking::ppDiffractiveScatter::EnableDebug (bool flag)"
Debug toggle - set to true or false to enable/disable debugging output 
.PP
\fBParameters:\fP
.RS 4
\fIdebug\fP Turn on and off debugging output
.RE
.PP
Debug toggle - set to true or false to enable/disable debugging output 
.SS "void ParticleTracking::ppDiffractiveScatter::GenerateDistribution (double energy)"
Generates the requried differential cross sections and integrates for the specified energy
.PP
Generates the required differential cross sections and integrates for the specified energy Generating pp Diffractive differential cross section
.PP
Integrating differential cross section
.PP
Diffractive Configuration generation done 
.SS "void ParticleTracking::ppDiffractiveScatter::GenerateDsigDtDxi (double energy)"
Generates the elastic differential cross section Places the results into the vectors t and DSig 
.PP
\fBParameters:\fP
.RS 4
\fIenergy\fP sqrt s 
.RE
.PP

.SS "double ParticleTracking::ppDiffractiveScatter::GetDiffractiveCrossSection () const"
Gets the Integrated Single diffractive cross section
.PP
Gets the Integrated elastic cross section 
.SS "double ParticleTracking::ppDiffractiveScatter::GetTMax () const"
Gets the currently set maximum t value 
.SS "double ParticleTracking::ppDiffractiveScatter::GetTMin () const"
Gets the currently set minimum t value
.PP
Gets the currently set minimum/maximum t value 
.SS "double ParticleTracking::ppDiffractiveScatter::GetTStepSize () const"
Gets the currently set t step size 
.SS "double ParticleTracking::ppDiffractiveScatter::GetXiMax () const"
Gets the currently set maximum xo value 
.SS "double ParticleTracking::ppDiffractiveScatter::GetXiMin () const"
Gets the currently set minimum xi value
.PP
Gets the currently set minimum/maximum t value 
.SS "double ParticleTracking::ppDiffractiveScatter::GetXiStepSize () const"
Gets the currently set xi step size 
.SS "void ParticleTracking::ppDiffractiveScatter::IntegrateDsigDtDxi ()"
Integrates the elastic differential cross section 
.SS "std::pair< double, double > ParticleTracking::ppDiffractiveScatter::Select ()"
set value of deltat depending on evaluation of (it<(N-1))
.PP
set value of deltax depending on evaluation of (ix<(N-1)) 
.SS "double ParticleTracking::ppDiffractiveScatter::SelectT ()"

.PP
Picks a t value from the generated distribution (including interpolation) Picks a t value from the generated distribution (including interpolation) 
.SS "double ParticleTracking::ppDiffractiveScatter::SelectXi ()"

.PP
Picks an Xi value from the generated distribution (including interpolation) Picks an xi value from the generated distribution (including interpolation) 
.SS "void ParticleTracking::ppDiffractiveScatter::SetTMax (double tmax)"
Sets the maximum t value for generation 
.SS "void ParticleTracking::ppDiffractiveScatter::SetTMin (double tmin)"
Sets the minimum t value for generation 
.PP
\fBParameters:\fP
.RS 4
\fItmin\fP the minimum t value to generate
.RE
.PP
Sets the minimum/maximum t value for generation 
.SS "void ParticleTracking::ppDiffractiveScatter::SetTStepSize (double StepSize)"
Sets the step size in t for the differential cross section generation 
.PP
\fBParameters:\fP
.RS 4
\fIstep\fP The step size to generate
.RE
.PP
Sets the step size in t for the differential cross section generation 
.SS "void ParticleTracking::ppDiffractiveScatter::SetXiMax (double ximax)"
Sets the maximum t value for generation 
.PP
\fBParameters:\fP
.RS 4
\fItmin\fP the minimum xi value to generate 
.RE
.PP

.SS "void ParticleTracking::ppDiffractiveScatter::SetXiMin (double min)"
Sets the minimum xi value for generation 
.PP
\fBParameters:\fP
.RS 4
\fItmin\fP the minimum xi value to generate
.RE
.PP
Sets the minimum/maximum t value for generation 
.SS "void ParticleTracking::ppDiffractiveScatter::SetXiStepSize (double StepSize)"
Sets the step size in Xi for the differential cross section generation 
.PP
\fBParameters:\fP
.RS 4
\fIstep\fP The step size to generate
.RE
.PP
Sets the step size in xi for the differential cross section generation 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
