.TH "ParticleTracking::ppElasticScatter" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::ppElasticScatter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElasticScatter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBppElasticScatter\fP ()"
.br
.ti -1c
.RI "void \fBGenerateTDistribution\fP (double energy)"
.br
.ti -1c
.RI "double \fBSelectT\fP ()"
.br
.ti -1c
.RI "void \fBSetTMin\fP (double tmin)"
.br
.ti -1c
.RI "void \fBSetTMax\fP (double)"
.br
.ti -1c
.RI "void \fBSetStepSize\fP (double)"
.br
.ti -1c
.RI "double \fBGetTMin\fP () const"
.br
.ti -1c
.RI "double \fBGetTMax\fP () const"
.br
.ti -1c
.RI "double \fBGetStepSize\fP () const"
.br
.ti -1c
.RI "double \fBGetElasticCrossSection\fP () const"
.br
.ti -1c
.RI "double \fBGetElasticCrossSectionN\fP () const"
.br
.ti -1c
.RI "double \fBPomeronScatter\fP (double t_input, double energy, bool em)"
.br
.ti -1c
.RI "void \fBEnableDebug\fP (bool)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for all things relating to proton-proton elastic scattering\&. This includes, generation of differential cross sections\&. Integration of the differential cross sections\&. Generation of momentum transfer t values for calculation of scattering angles\&. Multiple scattering models 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParticleTracking::ppElasticScatter::ppElasticScatter ()\fC [inline]\fP"
class constructor 
.SH "Member Function Documentation"
.PP 
.SS "void ParticleTracking::ppElasticScatter::EnableDebug (bool flag)"
Debug toggle - set to true or false to enable/disable debugging output 
.SS "void ParticleTracking::ppElasticScatter::GenerateTDistribution (double energy)"
Generates the requried differential cross sections and integrates for the specified energy 
.SS "double ParticleTracking::ppElasticScatter::GetElasticCrossSection () const"
Gets the Integrated elastic cross section 
.SS "double ParticleTracking::ppElasticScatter::GetElasticCrossSectionN () const"
Gets the Integrated elastic cross section 
.SS "double ParticleTracking::ppElasticScatter::GetStepSize () const"
Gets the currently set step size 
.SS "double ParticleTracking::ppElasticScatter::GetTMax () const"
Gets the currently set maximum t value 
.SS "double ParticleTracking::ppElasticScatter::GetTMin () const"
Gets the currently set minimum t value 
.SS "double ParticleTracking::ppElasticScatter::PomeronScatter (double t_input, double energy, bool em)"
Generates the differential cross section at a given t value and energy The energy is the sqrt(s) of the interaction 
.SS "double ParticleTracking::ppElasticScatter::SelectT ()"
Picks a t value from the generated distribution (including interpolation) 
.SS "void ParticleTracking::ppElasticScatter::SetStepSize (double StepSize)"
Sets the step size in t for the differential cross section generation 
.SS "void ParticleTracking::ppElasticScatter::SetTMax (double tmax)"
Sets the maximum t value for generation 
.SS "void ParticleTracking::ppElasticScatter::SetTMin (double tmin)"
Sets the minimum t value for generation 
.PP
\fBParameters:\fP
.RS 4
\fItmin\fP the minumum t value to generate
.RE
.PP
Sets the minimum t value for generation 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
