.TH "ParticleTracking::TRFMap" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::TRFMap
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTRFMap\fP (double g, double ds, double k1, double phi, double theta, double p0)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBPSvector\fP &x) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBcosTheta\fP"
.br
.ti -1c
.RI "double \fBsinTheta\fP"
.br
.ti -1c
.RI "double \fBgRed\fP"
.br
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBphi0\fP"
.br
.ti -1c
.RI "double \fBlen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
