.TH "ParticleTracking::SynchRadParticleProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::SynchRadParticleProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTBunchProc< B >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef double(* \fBPhotonGenerator\fP) (double)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSynchRadParticleProcess\fP (int prio, bool q=false)"
.br
.ti -1c
.RI "virtual void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &component)"
.br
.ti -1c
.RI "virtual void \fBDoProcess\fP (double ds)"
.br
.ti -1c
.RI "virtual double \fBGetMaxAllowedStepSize\fP () const"
.br
.ti -1c
.RI "void \fBIncludeQuadRadiation\fP (bool quadsr)"
.br
.ti -1c
.RI "void \fBSetNumComponentSteps\fP (int n)"
.br
.ti -1c
.RI "void \fBSetMaxComponentStepSize\fP (double ds_max)"
.br
.ti -1c
.RI "void \fBGeneratePhotons\fP (bool gp)"
.br
.ti -1c
.RI "void \fBAdjustBunchReferenceEnergy\fP (bool flg)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetPhotonGenerator\fP (PhotonGenerator pg)"
.br
.ti -1c
.RI "static void \fBUseSymplecticVariables\fP (bool flg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPHOTCONST1\fP"
.br
.ti -1c
.RI "double \fBPHOTCONST2\fP"
.br
.ti -1c
.RI "double \fBParticleMassMeV\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static PhotonGenerator \fBpgen\fP = HBSpectrumGen"
.br
.ti -1c
.RI "static bool \fBsympVars\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
