.TH "ParticleTracking::VerticalHaloParticleBunchFilter" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::VerticalHaloParticleBunchFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBParticleTracking::ParticleBunchFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBApply\fP (const \fBPSvector\fP &v) const"
.br
.ti -1c
.RI "void \fBSetVerticalLimit\fP (double)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
