.TH "ParticleTracking::CCFailureProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::CCFailureProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTBunchProc< B >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCFailureProcess\fP (int priority, int mode, \fBAcceleratorModel\fP *model, \fBLatticeFunctionTable\fP *twiss)"
.br
.ti -1c
.RI "\fBCCFailureProcess\fP (int priority, int mode, \fBAcceleratorModel\fP *model, \fBLatticeFunctionTable\fP *twiss, double freq, double crossing, double phase)"
.br
.ti -1c
.RI "\fBCCFailureProcess\fP (int priority, int mode, \fBAcceleratorModel\fP *model, \fBLatticeFunctionTable\fP *twiss, double freq, double crossing, double phase, int non_fail_turn, int fail_turn)"
.br
.ti -1c
.RI "virtual void \fBInitialiseProcess\fP (\fBBunch\fP &bunch)"
.br
.ti -1c
.RI "virtual void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &component)"
.br
.ti -1c
.RI "virtual void \fBDoProcess\fP (double ds)"
.br
.ti -1c
.RI "virtual double \fBGetMaxAllowedStepSize\fP () const"
.br
.ti -1c
.RI "virtual double \fBCalcM_12\fP (int start, int end, double deltamu, bool horizontal)"
.br
.ti -1c
.RI "virtual double \fBCalcM_22\fP (int start, int end, double deltamu, bool horizontal)"
.br
.ti -1c
.RI "virtual double \fBCalcM_12\fP (int start, int end, bool horizontal)"
.br
.ti -1c
.RI "virtual double \fBCalcM_22\fP (int start, int end, bool horizontal)"
.br
.ti -1c
.RI "virtual pair< double, double > \fBCalcMu\fP (int element)"
.br
.ti -1c
.RI "virtual pair< double, double > \fBCalcDeltaMu\fP (int element1, int element2)"
.br
.ti -1c
.RI "virtual double \fBCalcV1\fP (double M12)"
.br
.ti -1c
.RI "virtual double \fBCalcV1\fP (double deltamu, int n1, int n2, bool horizontal)"
.br
.ti -1c
.RI "virtual double \fBCalcV2\fP (double V1, double M22)"
.br
.ti -1c
.RI "virtual void \fBApplyPreCCKick\fP (\fBPSvector\fP &p, double V, double M12, bool horizontal)"
.br
.ti -1c
.RI "virtual void \fBApplyPostCCKick\fP (\fBPSvector\fP &p, double V, double M12, bool horizontal)"
.br
.ti -1c
.RI "virtual void \fBSetFailureOnOff\fP (bool onoff)"
.br
.ti -1c
.RI "virtual void \fBSetFailureTurns\fP (int ft)"
.br
.ti -1c
.RI "virtual void \fBSetNonFailureTurns\fP (int nft)"
.br
.ti -1c
.RI "virtual void \fBSetFailurePlanes\fP (bool hor, bool ver)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
