.TH "ParticleTracking::ParticleBunch" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleTracking::ParticleBunch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBunch\fP\&.
.PP
Inherited by \fBParticleTracking::ElectronBunch\fP, \fBParticleTracking::MuonBunch\fP, \fBParticleTracking::ProtonBunch\fP, and \fBSpinParticleBunch\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBParticle\fP \fBparticle_type\fP"
.br
.ti -1c
.RI "typedef PSvectorArray::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef PSvectorArray::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleBunch\fP (double P0, double \fBQ\fP, PSvectorArray &particles, double ParticleMass=ElectronMass, double ParticleMassMeV=ElectronMassMeV, double ParticleLifetime=\-1)"
.br
.ti -1c
.RI "\fBParticleBunch\fP (double P0, double \fBQ\fP, std::istream &is, double ParticleMass=ElectronMass, double ParticleMassMeV=ElectronMassMeV, double ParticleLifetime=\-1)"
.br
.ti -1c
.RI "\fBParticleBunch\fP (double P0, double Qm=1, double ParticleMass=ElectronMass, double ParticleMassMeV=ElectronMassMeV, double ParticleLifetime=\-1)"
.br
.ti -1c
.RI "virtual double \fBGetTotalCharge\fP () const"
.br
.ti -1c
.RI "virtual \fBPSmoments\fP & \fBGetMoments\fP (\fBPSmoments\fP &sigma) const"
.br
.ti -1c
.RI "virtual \fBPSmoments2D\fP & \fBGetProjectedMoments\fP (PScoord u, PScoord v, \fBPSmoments2D\fP &sigma) const"
.br
.ti -1c
.RI "virtual \fBPSvector\fP & \fBGetCentroid\fP (\fBPSvector\fP &p) const"
.br
.ti -1c
.RI "virtual \fBPoint2D\fP \fBGetProjectedCentroid\fP (PScoord u, PScoord v) const"
.br
.ti -1c
.RI "std::pair< double, double > \fBGetMoments\fP (PScoord u) const"
.br
.ti -1c
.RI "virtual double \fBAdjustRefMomentumToMean\fP ()"
.br
.ti -1c
.RI "virtual double \fBAdjustRefMomentum\fP (double dpp)"
.br
.ti -1c
.RI "virtual double \fBAdjustRefTimeToMean\fP ()"
.br
.ti -1c
.RI "virtual Histogram & \fBProjectDistribution\fP (PScoord axis, Histogram &hist) const"
.br
.ti -1c
.RI "virtual bool \fBApplyTransformation\fP (const \fBTransform3D\fP &t)"
.br
.ti -1c
.RI "virtual void \fBSortByCT\fP ()"
.br
.ti -1c
.RI "virtual void \fBOutput\fP (std::ostream &os) const"
.br
.ti -1c
.RI "virtual void \fBOutput\fP (std::ostream &os, bool show_header) const"
.br
.ti -1c
.RI "virtual void \fBOutputIndexParticle\fP (std::ostream &os, int index) const"
.br
.ti -1c
.RI "virtual void \fBInput\fP (double \fBQ\fP, std::istream &is)"
.br
.ti -1c
.RI "virtual size_t \fBAddParticle\fP (const \fBParticle\fP &p)"
.br
.ti -1c
.RI "void \fBSetMacroParticleCharge\fP (double q)"
.br
.ti -1c
.RI "ParticleBunch::iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "ParticleBunch::iterator \fBend\fP ()"
.br
.ti -1c
.RI "ParticleBunch::const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "ParticleBunch::const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "virtual void \fBpush_back\fP (const \fBParticle\fP &p)"
.br
.ti -1c
.RI "virtual ParticleBunch::iterator \fBerase\fP (ParticleBunch::iterator p)"
.br
.ti -1c
.RI "void \fBreserve\fP (const size_t n)"
.br
.ti -1c
.RI "PSvectorArray & \fBGetParticles\fP ()"
.br
.ti -1c
.RI "const PSvectorArray & \fBGetParticles\fP () const"
.br
.ti -1c
.RI "const \fBParticle\fP & \fBFirstParticle\fP () const"
.br
.ti -1c
.RI "\fBParticle\fP & \fBFirstParticle\fP ()"
.br
.ti -1c
.RI "void \fBSetCentroid\fP (const \fBParticle\fP &x0)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fBParticleBunch\fP newbunch)"
.br
.ti -1c
.RI "virtual int \fBScatter\fP (\fBParticle\fP &, double length, const \fBAperture\fP *)"
.br
.ti -1c
.RI "void \fBSetScatterConfigured\fP (bool)"
.br
.ti -1c
.RI "void \fBSetIntS\fP (double)"
.br
.ti -1c
.RI "double \fBGetIntS\fP ()"
.br
.ti -1c
.RI "virtual bool \fBIsStable\fP () const"
.br
.ti -1c
.RI "virtual double \fBGetParticleMass\fP () const"
.br
.ti -1c
.RI "virtual double \fBGetParticleMassMeV\fP () const"
.br
.ti -1c
.RI "virtual double \fBGetParticleLifetime\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBinit\fP"
.br
.ti -1c
.RI "int \fBcoords\fP"
.br
.ti -1c
.RI "bool \fBScatterConfigured\fP"
.br
.ti -1c
.RI "size_t \fBScatteringPhysicsModel\fP"
.br
.ti -1c
.RI "double \fBint_s\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "PSvectorArray \fBpArray\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "virtual int ParticleTracking::ParticleBunch::Scatter (\fBParticle\fP &, double length, const \fBAperture\fP *)\fC [inline]\fP, \fC [virtual]\fP"
Per-particle type scattering\&. This virtual function will be replaced in specific particle bunch classes to enable the relevant physics for each particle type (protons, electrons, etc)\&. 
.PP
Reimplemented in \fBParticleTracking::ProtonBunch\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
