.TH "PhaseAdvance" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhaseAdvance
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhaseAdvance\fP (\fBAcceleratorModel\fP *aModel, \fBLatticeFunctionTable\fP *aTwiss, double refMomentum)"
.br
.ti -1c
.RI "void \fBSetDelta\fP (double new_delta)"
.br
.ti -1c
.RI "void \fBScaleBendPathLength\fP (double scale)"
.br
.ti -1c
.RI "double \fBPhaseAdvanceBetween\fP (int n1, int n2, bool horizontal)"
.br
.ti -1c
.RI "double \fBPhaseAdvanceBetween\fP (string name1, string name2, bool horizontal)"
.br
.ti -1c
.RI "double \fBPhaseAdvanceBetween\fP (int n, bool horizontal)"
.br
.ti -1c
.RI "double \fBPhaseAdvanceBetween\fP (string name, bool horizontal)"
.br
.ti -1c
.RI "\fBRealMatrix\fP \fBTransferMapBetween\fP (int n1, int n2)"
.br
.ti -1c
.RI "double \fBGetPhaseAdvanceX\fP (int n2, int n1=0)"
.br
.ti -1c
.RI "double \fBGetPhaseAdvanceY\fP (int n2, int n1=0)"
.br
.ti -1c
.RI "pair< double, double > \fBCalcIntegerPart\fP (int n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
