.TH "PSvector" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSvector
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTPSMoments< N >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPSvector\fP (double x)"
.br
.ti -1c
.RI "double \fBx\fP () const"
.br
.ti -1c
.RI "double \fBy\fP () const"
.br
.ti -1c
.RI "double \fBct\fP () const"
.br
.ti -1c
.RI "double \fBxp\fP () const"
.br
.ti -1c
.RI "double \fByp\fP () const"
.br
.ti -1c
.RI "double \fBdp\fP () const"
.br
.ti -1c
.RI "double \fBtype\fP () const"
.br
.ti -1c
.RI "double \fBlocation\fP () const"
.br
.ti -1c
.RI "double \fBid\fP () const"
.br
.ti -1c
.RI "double \fBsd\fP () const"
.br
.ti -1c
.RI "double \fBoperator[]\fP (PScoord coord) const"
.br
.ti -1c
.RI "double & \fBx\fP ()"
.br
.ti -1c
.RI "double & \fBy\fP ()"
.br
.ti -1c
.RI "double & \fBct\fP ()"
.br
.ti -1c
.RI "double & \fBxp\fP ()"
.br
.ti -1c
.RI "double & \fByp\fP ()"
.br
.ti -1c
.RI "double & \fBdp\fP ()"
.br
.ti -1c
.RI "double & \fBtype\fP ()"
.br
.ti -1c
.RI "double & \fBlocation\fP ()"
.br
.ti -1c
.RI "double & \fBid\fP ()"
.br
.ti -1c
.RI "double & \fBsd\fP ()"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (PScoord coord)"
.br
.ti -1c
.RI "\fBoperator RealVector\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPSvector\fP &psv) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPSvector\fP &psv) const"
.br
.ti -1c
.RI "void \fBzero\fP ()"
.br
.ti -1c
.RI "\fBPSvector\fP & \fBoperator+=\fP (const \fBPSvector\fP &p)"
.br
.ti -1c
.RI "\fBPSvector\fP & \fBoperator\-=\fP (const \fBPSvector\fP &p)"
.br
.ti -1c
.RI "\fBPSvector\fP & \fBoperator*=\fP (double x)"
.br
.ti -1c
.RI "\fBPSvector\fP & \fBoperator/=\fP (double x)"
.br
.ti -1c
.RI "\fBPSvector\fP \fBoperator+\fP (const \fBPSvector\fP &rhs) const"
.br
.ti -1c
.RI "\fBPSvector\fP \fBoperator\-\fP (const \fBPSvector\fP &rhs) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBPSvector\fP &v)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBPSvector\fP &v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
