.TH "PureAxisRotation" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureAxisRotation
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRot3Drep\fP\&.
.PP
Inherited by \fBRotationX\fP, \fBRotationY\fP, and \fBRotationZ\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPureAxisRotation\fP (double phi)"
.br
.ti -1c
.RI "double \fBangle\fP () const"
.br
.ti -1c
.RI "double \fBsine\fP () const"
.br
.ti -1c
.RI "double \fBcosine\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPureAxisRotation\fP (double cosa, double sina)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
