.TH "R2Map" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
R2Map
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBR2Map\fP (double a11, double a12, double a21, double a22)"
.br
.ti -1c
.RI "double * \fBoperator[]\fP (int n)"
.br
.ti -1c
.RI "const double * \fBoperator[]\fP (int n) const"
.br
.ti -1c
.RI "bool \fBIsIdentity\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBr11\fP"
.br
.ti -1c
.RI "double \fBr12\fP"
.br
.ti -1c
.RI "double \fBr21\fP"
.br
.ti -1c
.RI "double \fBr22\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
class \fBR2Map\fP simple POD R matrix representation for one degree of freedom 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
