.TH "RandGenerator" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandGenerator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RandomNG\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandGenerator\fP (unsigned iseed=0)"
.br
.ti -1c
.RI "unsigned \fBgetSeed\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (unsigned iseed)"
.br
.ti -1c
.RI "double \fBnormal\fP (double mean, double variance)"
.br
.ti -1c
.RI "double \fBnormal\fP (double mean, double variance, double cutoff)"
.br
.ti -1c
.RI "double \fBuniform\fP (double low, double high)"
.br
.ti -1c
.RI "double \fBpoisson\fP (double u)"
.br
.ti -1c
.RI "double \fBlandau\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP (unsigned iseed=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class which represents a single random number generator\&. 
.SH "Member Function Documentation"
.PP 
.SS "void RandGenerator::init (unsigned iseed = \fC0\fP)"
Initialised the generator\&. Should be called before any other generator function\&. 
.SS "double RandGenerator::landau ()"
Generates a landau random number\&. 
.SS "double RandGenerator::normal (double mean, double variance)"
Generates a random number from a uniform (Gaussian) distribution with the specified mean and variance\&. 
.SS "double RandGenerator::normal (double mean, double variance, double cutoff)"
Generates a random number from a uniform (Gaussian) distribution with the specified mean and variance\&. The resulting distribution is truncated to +/-cutoff standard deviations\&. 
.SS "double RandGenerator::poisson (double u)"
Generates a poisson random number\&. 
.SS "void RandGenerator::reset ()"
Resets the seed for the generators to the last supplied seed value\&. 
.SS "void RandGenerator::reset (unsigned iseed)"
Resets the initial seed for the generator\&. 
.SS "double RandGenerator::uniform (double low, double high)"
Generates a uniform random number in the range |low,high> inclusive\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
