.TH "RandomInteger" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomInteger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomInteger\fP (long low, long high, \fBRNG\fP *gen)"
.br
.ti -1c
.RI "\fBRandomInteger\fP (long high, \fBRNG\fP *gen)"
.br
.ti -1c
.RI "\fBRandomInteger\fP (\fBRNG\fP *gen)"
.br
.ti -1c
.RI "long \fBlow\fP () const"
.br
.ti -1c
.RI "long \fBhigh\fP () const"
.br
.ti -1c
.RI "\fBRNG\fP * \fBgenerator\fP () const"
.br
.ti -1c
.RI "long \fBlow\fP (long x)"
.br
.ti -1c
.RI "long \fBhigh\fP (long x)"
.br
.ti -1c
.RI "\fBRNG\fP * \fBgenerator\fP (\fBRNG\fP *gen)"
.br
.ti -1c
.RI "long \fBasLong\fP ()"
.br
.ti -1c
.RI "long \fBoperator()\fP ()"
.br
.ti -1c
.RI "int \fBasInt\fP ()"
.br
.ti -1c
.RI "long \fBasLong\fP (long high)"
.br
.ti -1c
.RI "long \fBasLong\fP (long low, long high)"
.br
.ti -1c
.RI "long \fBoperator()\fP (long high)"
.br
.ti -1c
.RI "long \fBoperator()\fP (long low, long high)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "long \fB_asLong\fP (long, long)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBRNG\fP * \fBpGenerator\fP"
.br
.ti -1c
.RI "long \fBpLow\fP"
.br
.ti -1c
.RI "long \fBpHigh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
