.TH "RangeBase" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RangeBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNumericalRange< T, C >\fP, and \fBNumericalRange< double >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBResult\fP { \fBok\fP, \fBbelowlower\fP, \fBaboveupper\fP }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
