.TH "RectangularAperture" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RectangularAperture
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleApertures\&.h>\fP
.PP
Inherits \fBAperture\fP\&.
.PP
Inherited by \fBCollimatorAperture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangularAperture\fP (double width, double height)"
.br
.ti -1c
.RI "double \fBGetFullWidth\fP () const"
.br
.ti -1c
.RI "double \fBGetFullHeight\fP () const"
.br
.ti -1c
.RI "void \fBSetFullWidth\fP (double w)"
.br
.ti -1c
.RI "void \fBSetFullHeight\fP (double h)"
.br
.ti -1c
.RI "virtual bool \fBPointInside\fP (double x, double y, double z) const"
.br
.ti -1c
.RI "virtual double \fBGetRadiusAt\fP (double phi, double z) const"
.br
.ti -1c
.RI "virtual std::string \fBGetApertureType\fP () const"
.br
.ti -1c
.RI "virtual void \fBprintout\fP (std::ostream &out) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents an aperture with a rectangular cross-section\&. The aperture is assumed symmetric about the axis, and extruded along its geometry\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string RectangularAperture::GetApertureType () const\fC [inline]\fP, \fC [virtual]\fP"
Returns the type of the aperture\&. 
.PP
\fBReturns:\fP
.RS 4
A string containing the type of the aperture\&. 
.RE
.PP

.PP
Implements \fBAperture\fP\&.
.SS "double RectangularAperture::GetRadiusAt (double phi, double z) const\fC [virtual]\fP"
Returns the radius to the aperture at the angle phi\&. The z coordinate is ignored\&.
.PP
Rectangular \fBAperture\fP Functions 
.PP
Implements \fBAperture\fP\&.
.SS "bool RectangularAperture::PointInside (double x, double y, double z = \fC0\&.0\fP) const\fC [inline]\fP, \fC [virtual]\fP"
Returns true if the point (x,y,z) is within the aperture\&. The z coordinate is ignored\&. 
.PP
Implements \fBAperture\fP\&.
.PP
Reimplemented in \fBOneSidedUnalignedCollimatorAperture\fP, \fBUnalignedCollimatorAperture\fP, and \fBCollimatorAperture\fP\&.
.SS "void RectangularAperture::printout (std::ostream & out) const\fC [virtual]\fP"
Prints out the \fBAperture\fP parameters to a specified stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIout\fP The output stream to use\&. 
.RE
.PP

.PP
Reimplemented from \fBAperture\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
