.TH "ResistiveWakePotentials" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResistiveWakePotentials
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CollimatorPotentialModels\&.h>\fP
.PP
Inherits \fBCollimatorWakePotentials\fP, and \fBCollimatorWakePotentials\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResistiveWakePotentials\fP (int m, double r, double s, double l)"
.br
.ti -1c
.RI "virtual double \fBWlong\fP (double z, int m) const"
.br
.ti -1c
.RI "virtual double \fBWtrans\fP (double z, int m) const"
.br
.ti -1c
.RI "\fBResistiveWakePotentials\fP (int m, double r, double s, double l)"
.br
.ti -1c
.RI "double \fBWlong\fP (double z) const"
.br
.ti -1c
.RI "double \fBWtrans\fP (double z) const"
.br
.ti -1c
.RI "double \fBWtrans\fP (double z, int m) const"
.br
.ti -1c
.RI "double \fBWlong\fP (double z, int m) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
the resistive wake potentials (in MKS ssytem) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ResistiveWakePotentials::ResistiveWakePotentials (int m, double r, double s, double l)"
the resistive wake potentials (in MKS ssytem) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
