.TH "RFStructure" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RFStructure
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTAccCompGF_NC< RectangularGeometry, RFAcceleratingField >\fP\&.
.PP
Inherited by \fBSWRFStructure\fP, \fBTransverseRFStructure\fP, and \fBTWRFStructure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBGetFrequency\fP () const"
.br
.ti -1c
.RI "void \fBSetAmplitude\fP (double Epk)"
.br
.ti -1c
.RI "double \fBGetAmplitude\fP () const"
.br
.ti -1c
.RI "void \fBSetVoltage\fP (double v)"
.br
.ti -1c
.RI "void \fBSetPhase\fP (double phase)"
.br
.ti -1c
.RI "void \fBSetVoltagePhasor\fP (const \fBComplex\fP &z)"
.br
.ti -1c
.RI "double \fBGetVoltage\fP () const"
.br
.ti -1c
.RI "double \fBGetPhase\fP () const"
.br
.ti -1c
.RI "\fBComplex\fP \fBGetVoltagePhasor\fP () const"
.br
.ti -1c
.RI "double \fBGetBeamVoltage\fP () const"
.br
.ti -1c
.RI "double \fBGetWavelength\fP () const"
.br
.ti -1c
.RI "double \fBGetK\fP () const"
.br
.ti -1c
.RI "void \fBSetFrequency\fP (double f)"
.br
.ti -1c
.RI "void \fBSetWavelength\fP (double lambda)"
.br
.ti -1c
.RI "void \fBSetK\fP (double k)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBRFStructure\fP (const string &\fBid\fP, double len, \fBRFAcceleratingField\fP *aField)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
