.TH "Rotation3D" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rotation3D
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotation3D\fP (const \fBRotation3D\fP &R)"
.br
.ti -1c
.RI "const \fBRotation3D\fP & \fBoperator=\fP (const \fBRotation3D\fP &right)"
.br
.ti -1c
.RI "\fBPoint3D\fP \fBoperator()\fP (const \fBPoint3D\fP &x) const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator()\fP (const \fBVector3D\fP &v) const"
.br
.ti -1c
.RI "\fBRotation3D\fP \fBoperator*\fP (const \fBRotation3D\fP &R) const"
.br
.ti -1c
.RI "\fBPoint3D\fP \fBoperator*\fP (const \fBPoint3D\fP &p) const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator*\fP (const \fBVector3D\fP &v) const"
.br
.ti -1c
.RI "\fBRotation3D\fP \fBinv\fP () const"
.br
.ti -1c
.RI "RotationType \fBtype\fP () const"
.br
.ti -1c
.RI "bool \fBisIdentity\fP () const"
.br
.ti -1c
.RI "bool \fBisXrot\fP () const"
.br
.ti -1c
.RI "bool \fBisYrot\fP () const"
.br
.ti -1c
.RI "bool \fBisZrot\fP () const"
.br
.ti -1c
.RI "\fBRotation3D\fP \fBrotXbyPI\fP () const"
.br
.ti -1c
.RI "\fBRotation3D\fP \fBrotYbyPI\fP () const"
.br
.ti -1c
.RI "\fBRotation3D\fP \fBrotZbyPI\fP () const"
.br
.ti -1c
.RI "\fBRealMatrix\fP & \fBgetMatrix\fP (\fBRealMatrix\fP &m) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRotation3D\fP \fBidentity\fP ()"
.br
.ti -1c
.RI "static \fBRotation3D\fP \fBrotationX\fP (double angle)"
.br
.ti -1c
.RI "static \fBRotation3D\fP \fBrotationY\fP (double angle)"
.br
.ti -1c
.RI "static \fBRotation3D\fP \fBrotationZ\fP (double angle)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
