.TH "RWChannel" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RWChannel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBROChannel\fP\&.
.PP
Inherited by \fBTIRWChannel< E >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBWrite\fP (double value)=0"
.br
.ti -1c
.RI "virtual double \fBIncrement\fP (double delta)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
