.TH "SectorBend::PoleFaceInfo" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SectorBend::PoleFaceInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoleFaceInfo\fP (const \fBPoleFaceInfo\fP &rhs)"
.br
.ti -1c
.RI "\fBPoleFaceInfo\fP & \fBoperator=\fP (const \fBPoleFaceInfo\fP &rhs)"
.br
.ti -1c
.RI "void \fBSetInfo\fP (\fBPoleFace\fP *e1, \fBPoleFace\fP *e2)"
.br
.ti -1c
.RI "void \fBSetInfo\fP (\fBPoleFace\fP *e1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoleFace\fP * \fBentrance\fP"
.br
.ti -1c
.RI "\fBPoleFace\fP * \fBexit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
