.TH "SimpleATL" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleATL
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleATL\fP (double anA, const AcceleratorSupportList &supports, double vrms=0)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "double \fBDoStep\fP (double dt)"
.br
.ti -1c
.RI "void \fBRecordOffsets\fP (std::ostream &os) const"
.br
.ti -1c
.RI "double \fBGetTime\fP () const"
.br
.ti -1c
.RI "void \fBSetRandomSeed\fP (unsigned int nseed)"
.br
.ti -1c
.RI "unsigned int \fBGetRandomSeed\fP () const"
.br
.ti -1c
.RI "void \fBResetRandomSeed\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
