.TH "SMPTracking::ApplySolenoid" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPTracking::ApplySolenoid
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApplySolenoid\fP (double z, double kk)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBSliceMacroParticle\fP &p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBds\fP"
.br
.ti -1c
.RI "double \fBk\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
