.TH "SMPTracking::WakeFieldProcess" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPTracking::WakeFieldProcess
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTBunchProc< B >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBImpulseLocation\fP { \fBatCentre\fP, \fBatExit\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWakeFieldProcess\fP (int prio, double slice_width=1\&.0e\-6, string aID='SMP WAKEFIELD')"
.br
.ti -1c
.RI "virtual void \fBInitialiseProcess\fP (\fBBunch\fP &bunch)"
.br
.ti -1c
.RI "virtual void \fBSetCurrentComponent\fP (\fBAcceleratorComponent\fP &component)"
.br
.ti -1c
.RI "virtual void \fBDoProcess\fP (double ds)"
.br
.ti -1c
.RI "virtual double \fBGetMaxAllowedStepSize\fP () const"
.br
.ti -1c
.RI "void \fBApplyImpulseAt\fP (ImpulseLocation loc)"
.br
.ti -1c
.RI "void \fBIncludeTransverseWake\fP (bool flg)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
