.TH "SMPTracking::ApplyTWRF" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPTracking::ApplyTWRF
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApplyTWRF\fP (double p0, double ds1, double g1, double f1, double phi, bool entr_f, bool exit_f)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBSliceMacroParticle\fP &p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "double \fBg\fP"
.br
.ti -1c
.RI "double \fBds\fP"
.br
.ti -1c
.RI "double \fBphi0\fP"
.br
.ti -1c
.RI "double \fBE0\fP"
.br
.ti -1c
.RI "double \fBE1\fP"
.br
.ti -1c
.RI "bool \fBinc_entr_f\fP"
.br
.ti -1c
.RI "bool \fBinc_exit_f\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
