.TH "SMPTracking::ThinLensKick" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMPTracking::ThinLensKick
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThinLensKick\fP (const \fBComplex\fP &kk0, double kk1)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBSliceMacroParticle\fP &p) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBComplex\fP \fBk0\fP"
.br
.ti -1c
.RI "double \fBk1\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
