.TH "SpinVector" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpinVector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinVector\fP (double _x, double _y, double _z)"
.br
.ti -1c
.RI "double \fBx\fP () const"
.br
.ti -1c
.RI "double \fBy\fP () const"
.br
.ti -1c
.RI "double \fBz\fP () const"
.br
.ti -1c
.RI "double & \fBx\fP ()"
.br
.ti -1c
.RI "double & \fBy\fP ()"
.br
.ti -1c
.RI "double & \fBz\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
