.TH "StableOrbits" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StableOrbits
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStableOrbits\fP (\fBAcceleratorModel\fP *aModel)"
.br
.ti -1c
.RI "void \fBSelectStable\fP (\fBParticleBunch\fP &aBunch, list< size_t > *index)"
.br
.ti -1c
.RI "int \fBSetTurns\fP (int turns)"
.br
.ti -1c
.RI "int \fBSetObservationPoint\fP (int n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
