.TH "TAccCompG< G >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAccCompG< G >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAcceleratorComponent\fP\&.
.PP
Inherited by \fBTAccCompGF< G, F >\fP, and \fBTAccCompGF_NC< G, F >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef G \fBgeom_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTAccCompG\fP (const string &\fBid\fP, G *geom, \fBEMField\fP *field=nullptr)"
.br
.ti -1c
.RI "\fBTAccCompG\fP (const \fBTAccCompG\fP< G > &rhs)"
.br
.ti -1c
.RI "\fBTAccCompG\fP< G > & \fBoperator=\fP (const \fBTAccCompG\fP< G > &rhs)"
.br
.ti -1c
.RI "G & \fBGetGeometry\fP ()"
.br
.ti -1c
.RI "const G & \fBGetGeometry\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
