.TH "TAccCompGF_NC< G, F >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAccCompGF_NC< G, F >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTAccCompG< G >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef F \fBfield_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTAccCompGF_NC\fP (const string &\fBid\fP, G *geom, F *field)"
.br
.ti -1c
.RI "F & \fBGetField\fP ()"
.br
.ti -1c
.RI "const F & \fBGetField\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
