.TH "TBunchCMPTracker< _B >::B_Integrator" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBunchCMPTracker< _B >::B_Integrator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponentIntegrator\fP\&.
.PP
Inherited by \fBTBunchCMPTracker< _B >::Integrator< Drift >\fP, \fBTBunchCMPTracker< _B >::Integrator< Marker >\fP, \fBTBunchCMPTracker< _B >::Integrator< Monitor >\fP, \fBTBunchCMPTracker< _B >::Integrator< ParticleMapComponent >\fP, \fBTBunchCMPTracker< _B >::Integrator< RectMultipole >\fP, \fBTBunchCMPTracker< _B >::Integrator< SectorBend >\fP, \fBTBunchCMPTracker< _B >::Integrator< Solenoid >\fP, \fBTBunchCMPTracker< _B >::Integrator< SWRFStructure >\fP, \fBTBunchCMPTracker< _B >::Integrator< TransverseRFStructure >\fP, \fBTBunchCMPTracker< _B >::Integrator< TWRFStructure >\fP, and \fBTBunchCMPTracker< _B >::Integrator< _C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBunch\fP (_B &aBunch)"
.br
.ti -1c
.RI "virtual double \fBTrack\fP (double ds)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_B * \fBcurrentBunch\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
