.TH "TBunchProc< B >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBunchProc< B >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBunchProcess\fP\&.
.PP
Inherited by \fBParticleTracking::CCFailureProcess\fP, \fBParticleTracking::CollimateParticleProcess\fP, \fBParticleTracking::HollowELensProcess\fP, \fBParticleTracking::MonitorProcess\fP, \fBParticleTracking::NANCheckProcess\fP, \fBParticleTracking::RingDeltaTProcess\fP, \fBParticleTracking::SynchRadParticleProcess\fP, \fBParticleTracking::WakeFieldProcess\fP, \fBSMPTracking::WakeFieldProcess\fP, and \fBSpinParticleProcess\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTBunchProc\fP (const std::string &anID, int aPriority=0)"
.br
.ti -1c
.RI "virtual void \fBInitialiseProcess\fP (\fBBunch\fP &bunch)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "B * \fBcurrentBunch\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
