.TH "TComponentFrame< T >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TComponentFrame< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponentFrame\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBComponentType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTComponentFrame\fP (T &component)"
.br
.ti -1c
.RI "T & \fBGetComponent\fP ()"
.br
.ti -1c
.RI "const T & \fBGetComponent\fP () const"
.br
.ti -1c
.RI "T * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "const T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "virtual \fBModelElement\fP * \fBCopy\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<class T > \fBModelElement\fP * \fBTComponentFrame\fP< T >::Copy () const\fC [inline]\fP, \fC [virtual]\fP"
Virtual constructor\&. 
.PP
Reimplemented from \fBComponentFrame\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
