.TH "TIRWChannel< E >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIRWChannel< E >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRWChannel\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBTIC_ctor\fP< E > \fBch_ctor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTIRWChannel\fP (E *element, \fBTIC_ctor\fP< E > *proto_f)"
.br
.ti -1c
.RI "virtual string \fBGetID\fP () const"
.br
.ti -1c
.RI "virtual double \fBRead\fP () const"
.br
.ti -1c
.RI "virtual void \fBWrite\fP (double value)"
.br
.ti -1c
.RI "virtual double \fBIncrement\fP (double delta)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
