.TH "TLAS::MatrixDim" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TLAS::MatrixDim
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrixDim\fP (Dimension nrow, Dimension ncol)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMatrixDim\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBMatrixDim\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dimension \fBn\fP"
.br
.ti -1c
.RI "Dimension \fBm\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
