.TH "TLAS::ConstSubMatrix< T >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TLAS::ConstSubMatrix< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBVector\fP< T > \fBvector_type\fP"
.br
.ti -1c
.RI "typedef \fBMatrix\fP< T > \fBmatrix_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBoperator()\fP (Subscript i, Subscript j) const"
.br
.ti -1c
.RI "\fBoperator Matrix< T >\fP () const"
.br
.ti -1c
.RI "Dimension \fBnrows\fP () const"
.br
.ti -1c
.RI "Dimension \fBncols\fP () const"
.br
.ti -1c
.RI "\fBMatrixDim\fP \fBdim\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMatrix< T >\fP"
.br
.ti -1c
.RI "class \fBSubMatrix< T >\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
