.TH "TPSMoments< N >" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TPSMoments< N >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPSvector\fP, and \fBTCovMtrx< double, 2 *N >\fP\&.
.PP
Inherited by \fBSMPTracking::SliceMacroParticle\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBTCovMtrx\fP< double, 2 *N > \fBSigMtrx\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBmean\fP (int i) const"
.br
.ti -1c
.RI "double & \fBmean\fP (int i)"
.br
.ti -1c
.RI "void \fBprintFormatted\fP (std::ostream &os, bool norm=true) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
