.TH "TrackingOutputAV" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrackingOutputAV
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSimulationOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrackingOutputAV\fP (const std::string &filename)"
.br
.ti -1c
.RI "void \fBSuppressUnscattered\fP (const bool s)"
.br
.ti -1c
.RI "void \fBSetSRange\fP (double start, double end)"
.br
.ti -1c
.RI "void \fBSetTurn\fP (int inturn)"
.br
.ti -1c
.RI "void \fBSetTurnRange\fP (int start, int end)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRecord\fP (const \fBComponentFrame\fP *frame, const \fBBunch\fP *bunch)"
.br
.ti -1c
.RI "void \fBRecordInitialBunch\fP (const \fBBunch\fP *bunch)"
.br
.ti -1c
.RI "void \fBRecordFinalBunch\fP (const \fBBunch\fP *bunch)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
