.TH "Transformable" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transformable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGeometryPatch\fP, and \fBLatticeFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformable\fP (const \fBTransformable\fP &rhs)"
.br
.ti -1c
.RI "bool \fBIsTransformed\fP () const"
.br
.ti -1c
.RI "void \fBTranslate\fP (const \fBVector3D\fP &X)"
.br
.ti -1c
.RI "void \fBTranslate\fP (double x, double y, double z)"
.br
.ti -1c
.RI "void \fBTranslateX\fP (double dx)"
.br
.ti -1c
.RI "void \fBTranslateY\fP (double dy)"
.br
.ti -1c
.RI "void \fBTranslateZ\fP (double dz)"
.br
.ti -1c
.RI "void \fBRotateX\fP (double angle)"
.br
.ti -1c
.RI "void \fBRotateY\fP (double angle)"
.br
.ti -1c
.RI "void \fBRotateZ\fP (double angle)"
.br
.ti -1c
.RI "void \fBClearTransform\fP ()"
.br
.ti -1c
.RI "virtual void \fBInvalidate\fP () const"
.br
.ti -1c
.RI "const \fBTransform3D\fP * \fBGetTransformation\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformable\fP & \fBoperator=\fP (const \fBTransformable\fP &rhs)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTransform3D\fP * \fBlocal_T\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
