.TH "TransverseRFfield" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransverseRFfield
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRFAcceleratingField\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransverseRFfield\fP (double f, double Epk, double phase=0, double theta=0)"
.br
.ti -1c
.RI "virtual \fBVector3D\fP \fBGetBFieldAt\fP (const \fBPoint3D\fP &x, double t=0) const"
.br
.ti -1c
.RI "virtual \fBVector3D\fP \fBGetEFieldAt\fP (const \fBPoint3D\fP &x, double t=0) const"
.br
.ti -1c
.RI "virtual \fBVector3D\fP \fBGetForceAt\fP (const \fBPoint3D\fP &x, const \fBVector3D\fP &v, double q, double t=0) const"
.br
.ti -1c
.RI "virtual double \fBEr\fP (double z, double t) const"
.br
.ti -1c
.RI "double \fBGetFieldOrientation\fP () const"
.br
.ti -1c
.RI "void \fBSetFieldOrientation\fP (double t)"
.br
.ti -1c
.RI "virtual double \fBEz\fP (double z, double t) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBVector3D\fP TransverseRFfield::GetBFieldAt (const \fBPoint3D\fP & x, double t = \fC0\fP) const\fC [virtual]\fP"
Returns the magnetic field at the point x and time t\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The location of the particle\&. 
.br
\fIt\fP The time when the force is applied\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Vector3D containing the magnetic field\&. 
.RE
.PP

.PP
Implements \fBEMField\fP\&.
.SS "\fBVector3D\fP TransverseRFfield::GetEFieldAt (const \fBPoint3D\fP & x, double t = \fC0\fP) const\fC [virtual]\fP"
Returns the electric field at the point x and time t 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The location of the particle\&. 
.br
\fIt\fP The time when the force is applied\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Vector3D containing the electric field\&. 
.RE
.PP

.PP
Implements \fBEMField\fP\&.
.SS "\fBVector3D\fP TransverseRFfield::GetForceAt (const \fBPoint3D\fP & x, const \fBVector3D\fP & v, double q, double t = \fC0\fP) const\fC [virtual]\fP"
Returns the force due to this field on a particle of charge q with position x and velocity v at time t\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The location of the particle\&. 
.br
\fIv\fP The velocity of the particle\&. 
.br
\fIq\fP The charge of the particle\&. 
.br
\fIt\fP The time when the force is applied\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A Vector3D containing the force on a particle of charge q\&. 
.RE
.PP

.PP
Reimplemented from \fBEMField\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
