.TH "Transform3D" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transform3D
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransform3D\fP (const \fBPoint3D\fP &X, const \fBRotation3D\fP &R)"
.br
.ti -1c
.RI "\fBTransform3D\fP (const \fBTransform2D\fP &t2d)"
.br
.ti -1c
.RI "const \fBPoint3D\fP & \fBX\fP () const"
.br
.ti -1c
.RI "const \fBRotation3D\fP & \fBR\fP () const"
.br
.ti -1c
.RI "\fBPoint3D\fP \fBoperator()\fP (const \fBPoint3D\fP &p) const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator()\fP (const \fBVector3D\fP &v) const"
.br
.ti -1c
.RI "\fBPoint3D\fP \fBoperator*\fP (const \fBPoint3D\fP &p) const"
.br
.ti -1c
.RI "\fBVector3D\fP \fBoperator*\fP (const \fBVector3D\fP &v) const"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBoperator*\fP (const \fBTransform3D\fP &t) const"
.br
.ti -1c
.RI "const \fBTransform3D\fP & \fBoperator*=\fP (const \fBTransform3D\fP &t)"
.br
.ti -1c
.RI "\fBTransform3D\fP \fBinv\fP () const"
.br
.ti -1c
.RI "const \fBTransform3D\fP & \fBinvert\fP ()"
.br
.ti -1c
.RI "void \fBrotXbyPI\fP ()"
.br
.ti -1c
.RI "void \fBrotYbyPI\fP ()"
.br
.ti -1c
.RI "void \fBrotZbyPI\fP ()"
.br
.ti -1c
.RI "bool \fBisIdentity\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTransform3D\fP \fBrotationX\fP (double angle)"
.br
.ti -1c
.RI "static \fBTransform3D\fP \fBrotationY\fP (double angle)"
.br
.ti -1c
.RI "static \fBTransform3D\fP \fBrotationZ\fP (double angle)"
.br
.ti -1c
.RI "static \fBTransform3D\fP \fBtranslation\fP (double dx, double dy, double dz)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
