.TH "TransferMatrix" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransferMatrix
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransferMatrix\fP (\fBAcceleratorModel\fP *aModel, double refMomentum)"
.br
.ti -1c
.RI "void \fBFindTM\fP (\fBRealMatrix\fP &M)"
.br
.ti -1c
.RI "void \fBFindTM\fP (\fBRealMatrix\fP &M, \fBPSvector\fP &orbit)"
.br
.ti -1c
.RI "void \fBFindTM\fP (\fBRealMatrix\fP &M, \fBPSvector\fP &orbit, int n1, int n2)"
.br
.ti -1c
.RI "void \fBFindClosedOrbitTM\fP (\fBRealMatrix\fP &M, \fBPSvector\fP &orbit)"
.br
.ti -1c
.RI "void \fBRadiation\fP (bool flag)"
.br
.ti -1c
.RI "void \fBSetRadStepSize\fP (double rad_stepsize)"
.br
.ti -1c
.RI "void \fBSetRadNumSteps\fP (int rad_numsteps)"
.br
.ti -1c
.RI "void \fBScaleBendPathLength\fP (double scale)"
.br
.ti -1c
.RI "void \fBSetObservationPoint\fP (int n)"
.br
.ti -1c
.RI "void \fBSetDelta\fP (double new_delta)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
