.TH "Transform2D" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transform2D
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransform2D\fP (double dx=0, double dy=0, double dphi=0)"
.br
.ti -1c
.RI "\fBTransform2D\fP (const \fBRotation2D\fP &rr, const \fBPoint2D\fP &p=\fBPoint2D\fP(0, 0))"
.br
.ti -1c
.RI "\fBTransform2D\fP (const \fBPoint2D\fP &p)"
.br
.ti -1c
.RI "const \fBTransform2D\fP & \fBoperator*=\fP (const \fBTransform2D\fP &t)"
.br
.ti -1c
.RI "\fBTransform2D\fP \fBinv\fP () const"
.br
.ti -1c
.RI "const \fBTransform2D\fP & \fBinvert\fP ()"
.br
.ti -1c
.RI "const \fBPoint2D\fP & \fBtranslation\fP () const"
.br
.ti -1c
.RI "const \fBRotation2D\fP & \fBrotation\fP () const"
.br
.ti -1c
.RI "double \fBrotationAngle\fP () const"
.br
.ti -1c
.RI "double \fBsinphi\fP () const"
.br
.ti -1c
.RI "double \fBcosphi\fP () const"
.br
.ti -1c
.RI "bool \fBisIdentity\fP () const"
.br
.ti -1c
.RI "\fBPoint2D\fP \fBoperator()\fP (const \fBPoint2D\fP &p) const"
.br
.ti -1c
.RI "\fBVector2D\fP \fBoperator()\fP (const \fBVector2D\fP &v) const"
.br
.ti -1c
.RI "void \fBsetTranslationX\fP (double x)"
.br
.ti -1c
.RI "void \fBsetTranslationY\fP (double y)"
.br
.ti -1c
.RI "void \fBsetRotation\fP (double phi)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBTransform2D\fP \fBoperator*\fP (const \fBTransform2D\fP &t2, const \fBTransform2D\fP &t1)"
.br
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBTransform2D\fP &t)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBTransform2D\fP &t)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
