.TH "XTFFInterface::XTFF_Data" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XTFFInterface::XTFF_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator[]\fP (size_t n) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBkeywrd\fP"
.br
.ti -1c
.RI "std::string \fBlabel\fP"
.br
.ti -1c
.RI "std::string \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBfdn\fP"
.br
.ti -1c
.RI "double \fBrealdat\fP [11]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
