.TH "XTFFInterface" 3 "Fri Aug 4 2017" "Version 5.02" "Merlin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XTFFInterface
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBXTFF_Data\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXTFFInterface\fP (const std::string &fname, double nb=0, ostream *log=nullptr)"
.br
.ti -1c
.RI "\fBXTFFInterface\fP (double nb=0, ostream *log=nullptr)"
.br
.ti -1c
.RI "pair< \fBAcceleratorModel\fP *, \fBBeamData\fP * > \fBParse\fP ()"
.br
.ti -1c
.RI "pair< \fBAcceleratorModel\fP *, \fBBeamData\fP * > \fBParse\fP (double P_ref)"
.br
.ti -1c
.RI "void \fBAppendModel\fP (const std::string &fname)"
.br
.ti -1c
.RI "pair< \fBAcceleratorModel\fP *, \fBBeamData\fP * > \fBGetModel\fP ()"
.br
.ti -1c
.RI "void \fBIncludeApertures\fP (bool flag)"
.br
.ti -1c
.RI "void \fBTreatTypeAsDrift\fP (const string &)"
.br
.ti -1c
.RI "void \fBConstructGirders\fP (bool flg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Merlin from the source code\&.
